import { Language } from '@/lib/i18n/translations';

export interface Category {
  id: string;
  slug: string;
  icon: string;
  color: string;
  bgGradient: string;
  names: Record<Language, string>;
  descriptions: Record<Language, string>;
  toolCount: number;
}

export const categories: Category[] = [
  {
    id: 'math',
    slug: 'math',
    icon: '🧮',
    color: '#6366f1',
    bgGradient: 'from-indigo-500 to-purple-600',
    names: {
      en: 'Math Calculators',
      ar: 'الحاسبات الرياضية',
      fr: 'Calculatrices Mathématiques',
      es: 'Calculadoras Matemáticas',
      de: 'Mathematik-Rechner',
      zh: '数学计算器',
      hi: 'गणित कैलकुलेटर',
      pt: 'Calculadoras Matemáticas',
      ru: 'Математические Калькуляторы',
      ja: '数学計算機',
    },
    descriptions: {
      en: 'Solve equations, calculate percentages, fractions, algebra, geometry, and more.',
      ar: 'حل المعادلات وحساب النسب المئوية والكسور والجبر والهندسة وأكثر.',
      fr: 'Résolvez des équations, calculez des pourcentages, fractions, algèbre, géométrie et plus.',
      es: 'Resuelve ecuaciones, calcula porcentajes, fracciones, álgebra, geometría y más.',
      de: 'Lösen Sie Gleichungen, berechnen Sie Prozentsätze, Brüche, Algebra, Geometrie und mehr.',
      zh: '解方程、计算百分比、分数、代数、几何等。',
      hi: 'समीकरण हल करें, प्रतिशत, भिन्न, बीजगणित, ज्यामिति आदि की गणना करें।',
      pt: 'Resolva equações, calcule porcentagens, frações, álgebra, geometria e mais.',
      ru: 'Решайте уравнения, вычисляйте проценты, дроби, алгебру, геометрию и многое другое.',
      ja: '方程式を解き、パーセント、分数、代数、幾何学などを計算します。',
    },
    toolCount: 12,
  },
  {
    id: 'datetime',
    slug: 'datetime',
    icon: '📅',
    color: '#0ea5e9',
    bgGradient: 'from-sky-500 to-cyan-600',
    names: {
      en: 'Date & Time',
      ar: 'الوقت والتاريخ',
      fr: 'Date et Heure',
      es: 'Fecha y Hora',
      de: 'Datum und Zeit',
      zh: '日期时间',
      hi: 'दिनांक और समय',
      pt: 'Data e Hora',
      ru: 'Дата и Время',
      ja: '日付と時間',
    },
    descriptions: {
      en: 'Calculate age, date differences, time zones, countdowns, and calendar tools.',
      ar: 'احسب العمر وفروق التاريخ والمناطق الزمنية والعد التنازلي وأدوات التقويم.',
      fr: 'Calculez l\'âge, les différences de dates, les fuseaux horaires, les comptes à rebours et les outils de calendrier.',
      es: 'Calcula edad, diferencias de fechas, zonas horarias, cuentas atrás y herramientas de calendario.',
      de: 'Berechnen Sie Alter, Datumsunterschiede, Zeitzonen, Countdowns und Kalender-Tools.',
      zh: '计算年龄、日期差、时区、倒计时和日历工具。',
      hi: 'आयु, दिनांक अंतर, समय क्षेत्र, काउंटडाउन और कैलेंडर टूल्स की गणना करें।',
      pt: 'Calcule idade, diferenças de datas, fusos horários, contagens regressivas e ferramentas de calendário.',
      ru: 'Вычисляйте возраст, разницу дат, часовые пояса, обратные отсчёты и инструменты календаря.',
      ja: '年齢、日付差、タイムゾーン、カウントダウン、カレンダーツールを計算します。',
    },
    toolCount: 8,
  },
  {
    id: 'finance',
    slug: 'finance',
    icon: '💰',
    color: '#10b981',
    bgGradient: 'from-emerald-500 to-teal-600',
    names: {
      en: 'Finance Calculators',
      ar: 'الحاسبات المالية',
      fr: 'Calculatrices Financières',
      es: 'Calculadoras Financieras',
      de: 'Finanz-Rechner',
      zh: '金融计算器',
      hi: 'वित्त कैलकुलेटर',
      pt: 'Calculadoras Financeiras',
      ru: 'Финансовые Калькуляторы',
      ja: '金融計算機',
    },
    descriptions: {
      en: 'Loan payments, compound interest, mortgage, investment, currency converter.',
      ar: 'مدفوعات القروض والفائدة المركبة والرهن العقاري والاستثمار ومحول العملات.',
      fr: 'Remboursements de prêts, intérêts composés, hypothèque, investissement, convertisseur de devises.',
      es: 'Pagos de préstamos, interés compuesto, hipoteca, inversión, conversor de divisas.',
      de: 'Kreditraten, Zinseszins, Hypothek, Investition, Währungskonverter.',
      zh: '贷款还款、复利、抵押贷款、投资、货币转换器。',
      hi: 'ऋण भुगतान, चक्रवृद्धि ब्याज, बंधक, निवेश, मुद्रा परिवर्तक।',
      pt: 'Pagamentos de empréstimos, juros compostos, hipoteca, investimento, conversor de moedas.',
      ru: 'Платежи по кредиту, сложные проценты, ипотека, инвестиции, конвертер валют.',
      ja: 'ローン返済、複利、住宅ローン、投資、通貨コンバーター。',
    },
    toolCount: 10,
  },
  {
    id: 'health',
    slug: 'health',
    icon: '❤️',
    color: '#ef4444',
    bgGradient: 'from-rose-500 to-pink-600',
    names: {
      en: 'Health Calculators',
      ar: 'الحاسبات الصحية',
      fr: 'Calculatrices de Santé',
      es: 'Calculadoras de Salud',
      de: 'Gesundheits-Rechner',
      zh: '健康计算器',
      hi: 'स्वास्थ्य कैलकुलेटर',
      pt: 'Calculadoras de Saúde',
      ru: 'Калькуляторы Здоровья',
      ja: '健康計算機',
    },
    descriptions: {
      en: 'BMI, calorie intake, ideal weight, pregnancy calculator, heart rate zones.',
      ar: 'مؤشر كتلة الجسم وتناول السعرات الحرارية والوزن المثالي وحاسبة الحمل ومناطق معدل ضربات القلب.',
      fr: 'IMC, apport calorique, poids idéal, calculatrice de grossesse, zones de fréquence cardiaque.',
      es: 'IMC, ingesta calórica, peso ideal, calculadora de embarazo, zonas de frecuencia cardíaca.',
      de: 'BMI, Kalorienaufnahme, Idealgewicht, Schwangerschaftsrechner, Herzfrequenzzonen.',
      zh: 'BMI、卡路里摄入、理想体重、怀孕计算器、心率区间。',
      hi: 'BMI, कैलोरी सेवन, आदर्श वजन, गर्भावस्था कैलकुलेटर, हृदय गति क्षेत्र।',
      pt: 'IMC, ingestão calórica, peso ideal, calculadora de gravidez, zonas de frequência cardíaca.',
      ru: 'ИМТ, потребление калорий, идеальный вес, калькулятор беременности, зоны частоты сердечных сокращений.',
      ja: 'BMI、カロリー摂取量、理想体重、妊娠計算機、心拍ゾーン。',
    },
    toolCount: 9,
  },
  {
    id: 'converters',
    slug: 'converters',
    icon: '📏',
    color: '#f59e0b',
    bgGradient: 'from-amber-500 to-orange-600',
    names: {
      en: 'Unit Converters',
      ar: 'محولات الوحدات',
      fr: 'Convertisseurs d\'Unités',
      es: 'Conversores de Unidades',
      de: 'Einheitenkonverter',
      zh: '单位转换器',
      hi: 'इकाई परिवर्तक',
      pt: 'Conversores de Unidades',
      ru: 'Конвертеры Единиц',
      ja: '単位変換器',
    },
    descriptions: {
      en: 'Convert length, weight, temperature, volume, speed, pressure, and more.',
      ar: 'تحويل الطول والوزن ودرجة الحرارة والحجم والسرعة والضغط والمزيد.',
      fr: 'Convertissez la longueur, le poids, la température, le volume, la vitesse, la pression et plus.',
      es: 'Convierte longitud, peso, temperatura, volumen, velocidad, presión y más.',
      de: 'Konvertieren Sie Länge, Gewicht, Temperatur, Volumen, Geschwindigkeit, Druck und mehr.',
      zh: '转换长度、重量、温度、体积、速度、压力等。',
      hi: 'लंबाई, वजन, तापमान, आयतन, गति, दबाव आदि परिवर्तित करें।',
      pt: 'Converta comprimento, peso, temperatura, volume, velocidade, pressão e mais.',
      ru: 'Конвертируйте длину, вес, температуру, объём, скорость, давление и многое другое.',
      ja: '長さ、重さ、温度、体積、速度、圧力などを変換します。',
    },
    toolCount: 11,
  },
  {
    id: 'tech',
    slug: 'tech',
    icon: '💻',
    color: '#8b5cf6',
    bgGradient: 'from-violet-500 to-purple-600',
    names: {
      en: 'Tech Calculators',
      ar: 'الحاسبات التقنية',
      fr: 'Calculatrices Techniques',
      es: 'Calculadoras Técnicas',
      de: 'Technik-Rechner',
      zh: '技术计算器',
      hi: 'तकनीकी कैलकुलेटर',
      pt: 'Calculadoras Técnicas',
      ru: 'Технические Калькуляторы',
      ja: '技術計算機',
    },
    descriptions: {
      en: 'Binary, hex, color codes, bandwidth, storage, encoding, and developer tools.',
      ar: 'الثنائي والسداسي عشر وأكواد الألوان وعرض النطاق الترددي والتخزين والترميز وأدوات المطور.',
      fr: 'Binaire, hexadécimal, codes couleur, bande passante, stockage, encodage et outils de développeur.',
      es: 'Binario, hexadecimal, códigos de color, ancho de banda, almacenamiento, codificación y herramientas de desarrollador.',
      de: 'Binär, Hex, Farbcodes, Bandbreite, Speicher, Kodierung und Entwickler-Tools.',
      zh: '二进制、十六进制、颜色代码、带宽、存储、编码和开发工具。',
      hi: 'बाइनरी, हेक्स, रंग कोड, बैंडविड्थ, स्टोरेज, एनकोडिंग और डेवलपर टूल्स।',
      pt: 'Binário, hex, códigos de cor, largura de banda, armazenamento, codificação e ferramentas de desenvolvedor.',
      ru: 'Двоичный, шестнадцатеричный, цветовые коды, пропускная способность, хранилище, кодирование и инструменты разработчика.',
      ja: '2進数、16進数、カラーコード、帯域幅、ストレージ、エンコーディング、開発者ツール。',
    },
    toolCount: 9,
  },
  {
    id: 'everyday',
    slug: 'everyday',
    icon: '🚗',
    color: '#06b6d4',
    bgGradient: 'from-cyan-500 to-blue-600',
    names: {
      en: 'Everyday Life',
      ar: 'حاسبات الحياة اليومية',
      fr: 'Vie Quotidienne',
      es: 'Vida Cotidiana',
      de: 'Alltag',
      zh: '日常生活',
      hi: 'दैनिक जीवन',
      pt: 'Vida Cotidiana',
      ru: 'Повседневная Жизнь',
      ja: '日常生活',
    },
    descriptions: {
      en: 'Fuel cost, tip calculator, shopping discounts, cooking conversions, and more.',
      ar: 'تكلفة الوقود وحاسبة البقشيش وخصومات التسوق وتحويلات الطبخ والمزيد.',
      fr: 'Coût du carburant, pourboire, remises shopping, conversions culinaires et plus.',
      es: 'Costo de combustible, propinas, descuentos de compras, conversiones de cocina y más.',
      de: 'Kraftstoffkosten, Trinkgeld, Einkaufsrabatte, Koch-Umrechnungen und mehr.',
      zh: '燃油成本、小费计算器、购物折扣、烹饪换算等。',
      hi: 'ईंधन लागत, टिप कैलकुलेटर, खरीदारी छूट, खाना पकाने के रूपांतरण आदि।',
      pt: 'Custo de combustível, gorjeta, descontos de compras, conversões culinárias e mais.',
      ru: 'Стоимость топлива, чаевые, скидки на покупки, кулинарные конверсии и многое другое.',
      ja: '燃料費、チップ計算機、ショッピング割引、料理換算など。',
    },
    toolCount: 8,
  },
  {
    id: 'misc',
    slug: 'misc',
    icon: '🛠',
    color: '#64748b',
    bgGradient: 'from-slate-500 to-gray-600',
    names: {
      en: 'Miscellaneous Tools',
      ar: 'الأدوات المتنوعة',
      fr: 'Outils Divers',
      es: 'Herramientas Varias',
      de: 'Verschiedene Tools',
      zh: '其他工具',
      hi: 'विविध उपकरण',
      pt: 'Ferramentas Diversas',
      ru: 'Разные Инструменты',
      ja: 'その他のツール',
    },
    descriptions: {
      en: 'Password generator, random number, text tools, QR codes, and more utilities.',
      ar: 'مولد كلمات المرور والأرقام العشوائية وأدوات النص ورموز QR والمزيد من الأدوات المساعدة.',
      fr: 'Générateur de mot de passe, nombre aléatoire, outils texte, codes QR et plus.',
      es: 'Generador de contraseñas, número aleatorio, herramientas de texto, códigos QR y más.',
      de: 'Passwortgenerator, Zufallszahl, Textwerkzeuge, QR-Codes und weitere Hilfsprogramme.',
      zh: '密码生成器、随机数、文本工具、二维码等实用工具。',
      hi: 'पासवर्ड जनरेटर, रैंडम नंबर, टेक्स्ट टूल्स, QR कोड और अधिक उपयोगिताएं।',
      pt: 'Gerador de senha, número aleatório, ferramentas de texto, códigos QR e mais utilitários.',
      ru: 'Генератор паролей, случайные числа, текстовые инструменты, QR-коды и другие утилиты.',
      ja: 'パスワードジェネレーター、乱数、テキストツール、QRコード、その他のユーティリティ。',
    },
    toolCount: 7,
  },
];

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}
