import { Language } from '@/lib/i18n/translations';

export interface Tool {
  id: string;
  slug: string;
  categoryId: string;
  icon: string;
  isPopular?: boolean;
  isNew?: boolean;
  names: Record<Language, string>;
  descriptions: Record<Language, string>;
  metaTitles: Record<Language, string>;
  metaDescriptions: Record<Language, string>;
  keywords: Record<Language, string[]>;
}

export const tools: Tool[] = [
  // ===== MATH CALCULATORS =====
  {
    id: 'percentage',
    slug: 'percentage-calculator',
    categoryId: 'math',
    icon: '%',
    isPopular: true,
    names: {
      en: 'Percentage Calculator',
      ar: 'حاسبة النسبة المئوية',
      fr: 'Calculatrice de Pourcentage',
      es: 'Calculadora de Porcentaje',
      de: 'Prozentrechner',
      zh: '百分比计算器',
      hi: 'प्रतिशत कैलकुलेटर',
      pt: 'Calculadora de Porcentagem',
      ru: 'Калькулятор Процентов',
      ja: 'パーセント計算機',
    },
    descriptions: {
      en: 'Calculate percentages, find what percent one number is of another, and more.',
      ar: 'احسب النسب المئوية واعثر على النسبة المئوية لرقم من آخر والمزيد.',
      fr: 'Calculez des pourcentages, trouvez quel pourcentage un nombre est d\'un autre, et plus.',
      es: 'Calcula porcentajes, encuentra qué porcentaje es un número de otro, y más.',
      de: 'Berechnen Sie Prozentsätze, finden Sie heraus, wie viel Prozent eine Zahl von einer anderen ist.',
      zh: '计算百分比，找出一个数占另一个数的百分比，以及更多。',
      hi: 'प्रतिशत की गणना करें, एक संख्या दूसरे का कितना प्रतिशत है यह जानें।',
      pt: 'Calcule porcentagens, descubra que porcentagem um número é de outro.',
      ru: 'Вычисляйте проценты, находите, каким процентом одно число является от другого.',
      ja: 'パーセントを計算し、ある数が別の数の何パーセントかを求めます。',
    },
    metaTitles: {
      en: 'Percentage Calculator – Calculate Percentages Online Free',
      ar: 'حاسبة النسبة المئوية – احسب النسب المئوية مجانًا',
      fr: 'Calculatrice de Pourcentage – Calculez des Pourcentages en Ligne',
      es: 'Calculadora de Porcentaje – Calcula Porcentajes Online Gratis',
      de: 'Prozentrechner – Prozentsätze Online Berechnen',
      zh: '百分比计算器 – 在线免费计算百分比',
      hi: 'प्रतिशत कैलकुलेटर – ऑनलाइन प्रतिशत की गणना करें',
      pt: 'Calculadora de Porcentagem – Calcule Porcentagens Online',
      ru: 'Калькулятор Процентов – Вычислите Проценты Онлайн',
      ja: 'パーセント計算機 – オンラインで無料でパーセントを計算',
    },
    metaDescriptions: {
      en: 'Free online percentage calculator. Calculate percentages, find percent of a number, percentage increase/decrease, and more.',
      ar: 'حاسبة النسبة المئوية المجانية عبر الإنترنت. احسب النسب المئوية وجد النسبة المئوية لأي رقم.',
      fr: 'Calculatrice de pourcentage gratuite en ligne. Calculez des pourcentages, trouvez le pourcentage d\'un nombre.',
      es: 'Calculadora de porcentaje gratuita en línea. Calcula porcentajes, encuentra el porcentaje de un número.',
      de: 'Kostenloser Online-Prozentrechner. Berechnen Sie Prozentsätze, finden Sie den Prozentsatz einer Zahl.',
      zh: '免费在线百分比计算器。计算百分比，找出一个数的百分比。',
      hi: 'मुफ्त ऑनलाइन प्रतिशत कैलकुलेटर। प्रतिशत की गणना करें, किसी संख्या का प्रतिशत जानें।',
      pt: 'Calculadora de porcentagem gratuita online. Calcule porcentagens, encontre a porcentagem de um número.',
      ru: 'Бесплатный онлайн-калькулятор процентов. Вычисляйте проценты, находите процент числа.',
      ja: '無料のオンラインパーセント計算機。パーセントを計算し、数値のパーセントを求めます。',
    },
    keywords: {
      en: ['percentage calculator', 'percent calculator', 'percentage of number'],
      ar: ['حاسبة النسبة المئوية', 'حساب النسبة المئوية'],
      fr: ['calculatrice pourcentage', 'calculer pourcentage'],
      es: ['calculadora porcentaje', 'calcular porcentaje'],
      de: ['Prozentrechner', 'Prozent berechnen'],
      zh: ['百分比计算器', '计算百分比'],
      hi: ['प्रतिशत कैलकुलेटर', 'प्रतिशत गणना'],
      pt: ['calculadora porcentagem', 'calcular porcentagem'],
      ru: ['калькулятор процентов', 'вычислить процент'],
      ja: ['パーセント計算機', 'パーセント計算'],
    },
  },
  {
    id: 'fraction',
    slug: 'fraction-calculator',
    categoryId: 'math',
    icon: '½',
    names: {
      en: 'Fraction Calculator',
      ar: 'حاسبة الكسور',
      fr: 'Calculatrice de Fractions',
      es: 'Calculadora de Fracciones',
      de: 'Bruchrechner',
      zh: '分数计算器',
      hi: 'भिन्न कैलकुलेटर',
      pt: 'Calculadora de Frações',
      ru: 'Калькулятор Дробей',
      ja: '分数計算機',
    },
    descriptions: {
      en: 'Add, subtract, multiply, and divide fractions with step-by-step solutions.',
      ar: 'جمع وطرح وضرب وقسمة الكسور مع الحلول خطوة بخطوة.',
      fr: 'Additionnez, soustrayez, multipliez et divisez des fractions avec des solutions étape par étape.',
      es: 'Suma, resta, multiplica y divide fracciones con soluciones paso a paso.',
      de: 'Addieren, subtrahieren, multiplizieren und dividieren Sie Brüche mit Schritt-für-Schritt-Lösungen.',
      zh: '加减乘除分数，并提供逐步解题过程。',
      hi: 'चरण-दर-चरण समाधान के साथ भिन्नों को जोड़ें, घटाएं, गुणा करें और विभाजित करें।',
      pt: 'Some, subtraia, multiplique e divida frações com soluções passo a passo.',
      ru: 'Складывайте, вычитайте, умножайте и делите дроби с пошаговыми решениями.',
      ja: 'ステップバイステップの解答で分数の加減乗除を計算します。',
    },
    metaTitles: {
      en: 'Fraction Calculator – Add, Subtract, Multiply & Divide Fractions',
      ar: 'حاسبة الكسور – جمع وطرح وضرب وقسمة الكسور',
      fr: 'Calculatrice de Fractions – Additionner, Soustraire, Multiplier et Diviser',
      es: 'Calculadora de Fracciones – Suma, Resta, Multiplica y Divide',
      de: 'Bruchrechner – Brüche Addieren, Subtrahieren, Multiplizieren & Dividieren',
      zh: '分数计算器 – 加减乘除分数',
      hi: 'भिन्न कैलकुलेटर – भिन्न जोड़ें, घटाएं, गुणा और विभाजित करें',
      pt: 'Calculadora de Frações – Somar, Subtrair, Multiplicar e Dividir',
      ru: 'Калькулятор Дробей – Сложение, Вычитание, Умножение и Деление Дробей',
      ja: '分数計算機 – 分数の加算、減算、乗算、除算',
    },
    metaDescriptions: {
      en: 'Free online fraction calculator. Perform arithmetic operations on fractions with detailed step-by-step solutions.',
      ar: 'حاسبة الكسور المجانية. أجرِ عمليات حسابية على الكسور مع حلول تفصيلية.',
      fr: 'Calculatrice de fractions gratuite. Effectuez des opérations arithmétiques sur des fractions.',
      es: 'Calculadora de fracciones gratuita. Realiza operaciones aritméticas con fracciones.',
      de: 'Kostenloser Bruchrechner. Führen Sie arithmetische Operationen mit Brüchen durch.',
      zh: '免费在线分数计算器。对分数进行算术运算，并提供详细的逐步解答。',
      hi: 'मुफ्त ऑनलाइन भिन्न कैलकुलेटर। भिन्नों पर अंकगणित संचालन करें।',
      pt: 'Calculadora de frações gratuita. Realize operações aritméticas com frações.',
      ru: 'Бесплатный калькулятор дробей. Выполняйте арифметические операции с дробями.',
      ja: '無料の分数計算機。分数の算術演算を実行します。',
    },
    keywords: {
      en: ['fraction calculator', 'add fractions', 'subtract fractions', 'divide fractions'],
      ar: ['حاسبة كسور', 'جمع كسور'],
      fr: ['calculatrice fractions', 'additionner fractions'],
      es: ['calculadora fracciones', 'sumar fracciones'],
      de: ['Bruchrechner', 'Brüche addieren'],
      zh: ['分数计算器', '分数加法'],
      hi: ['भिन्न कैलकुलेटर', 'भिन्न जोड़ें'],
      pt: ['calculadora frações', 'somar frações'],
      ru: ['калькулятор дробей', 'сложить дроби'],
      ja: ['分数計算機', '分数の計算'],
    },
  },
  {
    id: 'scientific',
    slug: 'scientific-calculator',
    categoryId: 'math',
    icon: '🔬',
    isPopular: true,
    names: {
      en: 'Scientific Calculator',
      ar: 'الآلة الحاسبة العلمية',
      fr: 'Calculatrice Scientifique',
      es: 'Calculadora Científica',
      de: 'Wissenschaftlicher Rechner',
      zh: '科学计算器',
      hi: 'वैज्ञानिक कैलकुलेटर',
      pt: 'Calculadora Científica',
      ru: 'Научный Калькулятор',
      ja: '関数電卓',
    },
    descriptions: {
      en: 'Advanced scientific calculator with trigonometry, logarithms, powers, and more.',
      ar: 'آلة حاسبة علمية متقدمة مع حساب المثلثات واللوغاريتمات والقوى والمزيد.',
      fr: 'Calculatrice scientifique avancée avec trigonométrie, logarithmes, puissances et plus.',
      es: 'Calculadora científica avanzada con trigonometría, logaritmos, potencias y más.',
      de: 'Fortgeschrittener wissenschaftlicher Rechner mit Trigonometrie, Logarithmen, Potenzen und mehr.',
      zh: '具有三角函数、对数、幂次等高级功能的科学计算器。',
      hi: 'त्रिकोणमिति, लघुगणक, घात और अधिक के साथ उन्नत वैज्ञानिक कैलकुलेटर।',
      pt: 'Calculadora científica avançada com trigonometria, logaritmos, potências e mais.',
      ru: 'Расширенный научный калькулятор с тригонометрией, логарифмами, степенями и многим другим.',
      ja: '三角関数、対数、べき乗などを備えた高度な関数電卓。',
    },
    metaTitles: {
      en: 'Scientific Calculator – Online Advanced Math Calculator',
      ar: 'الآلة الحاسبة العلمية – حاسبة رياضيات متقدمة عبر الإنترنت',
      fr: 'Calculatrice Scientifique – Calculatrice Mathématique Avancée en Ligne',
      es: 'Calculadora Científica – Calculadora Matemática Avanzada Online',
      de: 'Wissenschaftlicher Rechner – Online Fortgeschrittener Mathematik-Rechner',
      zh: '科学计算器 – 在线高级数学计算器',
      hi: 'वैज्ञानिक कैलकुलेटर – ऑनलाइन उन्नत गणित कैलकुलेटर',
      pt: 'Calculadora Científica – Calculadora Matemática Avançada Online',
      ru: 'Научный Калькулятор – Онлайн Расширенный Математический Калькулятор',
      ja: '関数電卓 – オンライン高度数学計算機',
    },
    metaDescriptions: {
      en: 'Free online scientific calculator with trigonometric functions, logarithms, and advanced math operations.',
      ar: 'آلة حاسبة علمية مجانية مع دوال مثلثية ولوغاريتمات وعمليات رياضية متقدمة.',
      fr: 'Calculatrice scientifique gratuite avec fonctions trigonométriques, logarithmes.',
      es: 'Calculadora científica gratuita con funciones trigonométricas, logaritmos.',
      de: 'Kostenloser wissenschaftlicher Rechner mit trigonometrischen Funktionen, Logarithmen.',
      zh: '免费在线科学计算器，具有三角函数、对数和高级数学运算。',
      hi: 'त्रिकोणमितीय फ़ंक्शन, लघुगणक के साथ मुफ्त ऑनलाइन वैज्ञानिक कैलकुलेटर।',
      pt: 'Calculadora científica gratuita com funções trigonométricas, logaritmos.',
      ru: 'Бесплатный научный калькулятор с тригонометрическими функциями, логарифмами.',
      ja: '三角関数、対数を備えた無料のオンライン関数電卓。',
    },
    keywords: {
      en: ['scientific calculator', 'online calculator', 'trigonometry calculator'],
      ar: ['آلة حاسبة علمية', 'حاسبة علمية'],
      fr: ['calculatrice scientifique', 'calculatrice en ligne'],
      es: ['calculadora científica', 'calculadora online'],
      de: ['wissenschaftlicher Rechner', 'Online-Rechner'],
      zh: ['科学计算器', '在线计算器'],
      hi: ['वैज्ञानिक कैलकुलेटर', 'ऑनलाइन कैलकुलेटर'],
      pt: ['calculadora científica', 'calculadora online'],
      ru: ['научный калькулятор', 'онлайн калькулятор'],
      ja: ['関数電卓', 'オンライン計算機'],
    },
  },
  {
    id: 'square-root',
    slug: 'square-root-calculator',
    categoryId: 'math',
    icon: '√',
    names: {
      en: 'Square Root Calculator',
      ar: 'حاسبة الجذر التربيعي',
      fr: 'Calculatrice de Racine Carrée',
      es: 'Calculadora de Raíz Cuadrada',
      de: 'Quadratwurzelrechner',
      zh: '平方根计算器',
      hi: 'वर्गमूल कैलकुलेटर',
      pt: 'Calculadora de Raiz Quadrada',
      ru: 'Калькулятор Квадратного Корня',
      ja: '平方根計算機',
    },
    descriptions: {
      en: 'Calculate square roots, cube roots, and nth roots of any number instantly.',
      ar: 'احسب الجذور التربيعية والتكعيبية والجذور من الدرجة n لأي رقم فورًا.',
      fr: 'Calculez les racines carrées, cubiques et n-ièmes de n\'importe quel nombre instantanément.',
      es: 'Calcula raíces cuadradas, cúbicas y enésimas de cualquier número al instante.',
      de: 'Berechnen Sie Quadratwurzeln, Kubikwurzeln und n-te Wurzeln einer beliebigen Zahl sofort.',
      zh: '即时计算任意数的平方根、立方根和n次方根。',
      hi: 'किसी भी संख्या का वर्गमूल, घनमूल और n-वां मूल तुरंत गणना करें।',
      pt: 'Calcule raízes quadradas, cúbicas e n-ésimas de qualquer número instantaneamente.',
      ru: 'Мгновенно вычисляйте квадратные корни, кубические корни и корни n-й степени.',
      ja: '任意の数の平方根、立方根、n乗根を即座に計算します。',
    },
    metaTitles: {
      en: 'Square Root Calculator – Calculate Roots of Numbers',
      ar: 'حاسبة الجذر التربيعي – احسب جذور الأعداد',
      fr: 'Calculatrice de Racine Carrée – Calculez les Racines des Nombres',
      es: 'Calculadora de Raíz Cuadrada – Calcula Raíces de Números',
      de: 'Quadratwurzelrechner – Wurzeln von Zahlen Berechnen',
      zh: '平方根计算器 – 计算数字的根',
      hi: 'वर्गमूल कैलकुलेटर – संख्याओं की मूल गणना करें',
      pt: 'Calculadora de Raiz Quadrada – Calcule Raízes de Números',
      ru: 'Калькулятор Квадратного Корня – Вычислите Корни Чисел',
      ja: '平方根計算機 – 数字の平方根を計算',
    },
    metaDescriptions: {
      en: 'Free online square root calculator. Find square roots, cube roots, and nth roots with detailed solutions.',
      ar: 'حاسبة الجذر التربيعي المجانية. احسب الجذور التربيعية والتكعيبية مع حلول تفصيلية.',
      fr: 'Calculatrice de racine carrée gratuite. Trouvez les racines carrées, cubiques avec des solutions détaillées.',
      es: 'Calculadora de raíz cuadrada gratuita. Encuentra raíces cuadradas y cúbicas con soluciones detalladas.',
      de: 'Kostenloser Quadratwurzelrechner. Finden Sie Quadratwurzeln, Kubikwurzeln mit detaillierten Lösungen.',
      zh: '免费在线平方根计算器。找出平方根、立方根，并提供详细解答。',
      hi: 'मुफ्त ऑनलाइन वर्गमूल कैलकुलेटर। विस्तृत समाधान के साथ वर्गमूल और घनमूल खोजें।',
      pt: 'Calculadora de raiz quadrada gratuita. Encontre raízes quadradas e cúbicas com soluções detalhadas.',
      ru: 'Бесплатный калькулятор квадратного корня. Найдите квадратные и кубические корни с подробными решениями.',
      ja: '無料の平方根計算機。詳細な解答で平方根と立方根を計算します。',
    },
    keywords: {
      en: ['square root calculator', 'sqrt calculator', 'root of number'],
      ar: ['حاسبة جذر تربيعي', 'جذر تربيعي'],
      fr: ['calculatrice racine carrée', 'racine carrée'],
      es: ['calculadora raíz cuadrada', 'raíz cuadrada'],
      de: ['Quadratwurzelrechner', 'Quadratwurzel'],
      zh: ['平方根计算器', '平方根'],
      hi: ['वर्गमूल कैलकुलेटर', 'वर्गमूल'],
      pt: ['calculadora raiz quadrada', 'raiz quadrada'],
      ru: ['калькулятор квадратного корня', 'квадратный корень'],
      ja: ['平方根計算機', '平方根'],
    },
  },
  // ===== DATE & TIME =====
  {
    id: 'age',
    slug: 'age-calculator',
    categoryId: 'datetime',
    icon: '🎂',
    isPopular: true,
    names: {
      en: 'Age Calculator',
      ar: 'حاسبة العمر',
      fr: 'Calculatrice d\'Âge',
      es: 'Calculadora de Edad',
      de: 'Altersrechner',
      zh: '年龄计算器',
      hi: 'आयु कैलकुलेटर',
      pt: 'Calculadora de Idade',
      ru: 'Калькулятор Возраста',
      ja: '年齢計算機',
    },
    descriptions: {
      en: 'Calculate your exact age in years, months, days, hours, and minutes from your birth date.',
      ar: 'احسب عمرك الدقيق بالسنوات والأشهر والأيام والساعات والدقائق من تاريخ ميلادك.',
      fr: 'Calculez votre âge exact en années, mois, jours, heures et minutes à partir de votre date de naissance.',
      es: 'Calcula tu edad exacta en años, meses, días, horas y minutos desde tu fecha de nacimiento.',
      de: 'Berechnen Sie Ihr genaues Alter in Jahren, Monaten, Tagen, Stunden und Minuten.',
      zh: '从出生日期计算您的确切年龄（年、月、日、小时和分钟）。',
      hi: 'अपनी जन्म तिथि से वर्षों, महीनों, दिनों, घंटों और मिनटों में अपनी सटीक आयु की गणना करें।',
      pt: 'Calcule sua idade exata em anos, meses, dias, horas e minutos a partir da data de nascimento.',
      ru: 'Вычислите свой точный возраст в годах, месяцах, днях, часах и минутах от даты рождения.',
      ja: '生年月日から年、月、日、時間、分で正確な年齢を計算します。',
    },
    metaTitles: {
      en: 'Age Calculator – Calculate Your Exact Age Online',
      ar: 'حاسبة العمر – احسب عمرك الدقيق عبر الإنترنت',
      fr: 'Calculatrice d\'Âge – Calculez Votre Âge Exact en Ligne',
      es: 'Calculadora de Edad – Calcula tu Edad Exacta Online',
      de: 'Altersrechner – Berechnen Sie Ihr Genaues Alter Online',
      zh: '年龄计算器 – 在线计算您的确切年龄',
      hi: 'आयु कैलकुलेटर – ऑनलाइन अपनी सटीक आयु गणना करें',
      pt: 'Calculadora de Idade – Calcule sua Idade Exata Online',
      ru: 'Калькулятор Возраста – Вычислите Свой Точный Возраст Онлайн',
      ja: '年齢計算機 – オンラインで正確な年齢を計算',
    },
    metaDescriptions: {
      en: 'Free online age calculator. Find your exact age in years, months, and days from your birth date.',
      ar: 'حاسبة العمر المجانية. احسب عمرك الدقيق بالسنوات والأشهر والأيام من تاريخ ميلادك.',
      fr: 'Calculatrice d\'âge gratuite. Trouvez votre âge exact en années, mois et jours.',
      es: 'Calculadora de edad gratuita. Encuentra tu edad exacta en años, meses y días.',
      de: 'Kostenloser Altersrechner. Finden Sie Ihr genaues Alter in Jahren, Monaten und Tagen.',
      zh: '免费在线年龄计算器。从出生日期计算您的确切年龄（年、月、日）。',
      hi: 'मुफ्त ऑनलाइन आयु कैलकुलेटर। जन्म तिथि से वर्षों, महीनों और दिनों में सटीक आयु जानें।',
      pt: 'Calculadora de idade gratuita. Encontre sua idade exata em anos, meses e dias.',
      ru: 'Бесплатный калькулятор возраста. Найдите свой точный возраст в годах, месяцах и днях.',
      ja: '無料のオンライン年齢計算機。生年月日から年、月、日で正確な年齢を求めます。',
    },
    keywords: {
      en: ['age calculator', 'how old am I', 'birth date calculator'],
      ar: ['حاسبة العمر', 'كم عمري', 'حساب تاريخ الميلاد'],
      fr: ['calculatrice âge', 'quel âge ai-je'],
      es: ['calculadora edad', 'cuántos años tengo'],
      de: ['Altersrechner', 'wie alt bin ich'],
      zh: ['年龄计算器', '我多少岁'],
      hi: ['आयु कैलकुलेटर', 'मेरी उम्र कितनी है'],
      pt: ['calculadora idade', 'quantos anos tenho'],
      ru: ['калькулятор возраста', 'сколько мне лет'],
      ja: ['年齢計算機', '何歳'],
    },
  },
  {
    id: 'date-difference',
    slug: 'date-difference-calculator',
    categoryId: 'datetime',
    icon: '📆',
    names: {
      en: 'Date Difference Calculator',
      ar: 'حاسبة الفرق بين التاريخين',
      fr: 'Calculatrice de Différence de Dates',
      es: 'Calculadora de Diferencia de Fechas',
      de: 'Datumsunterschiedrechner',
      zh: '日期差计算器',
      hi: 'तिथि अंतर कैलकुलेटर',
      pt: 'Calculadora de Diferença de Datas',
      ru: 'Калькулятор Разницы Дат',
      ja: '日付差計算機',
    },
    descriptions: {
      en: 'Calculate the number of days, weeks, months, and years between two dates.',
      ar: 'احسب عدد الأيام والأسابيع والأشهر والسنوات بين تاريخين.',
      fr: 'Calculez le nombre de jours, semaines, mois et années entre deux dates.',
      es: 'Calcula el número de días, semanas, meses y años entre dos fechas.',
      de: 'Berechnen Sie die Anzahl der Tage, Wochen, Monate und Jahre zwischen zwei Daten.',
      zh: '计算两个日期之间的天数、周数、月数和年数。',
      hi: 'दो तिथियों के बीच दिनों, सप्ताहों, महीनों और वर्षों की संख्या की गणना करें।',
      pt: 'Calcule o número de dias, semanas, meses e anos entre duas datas.',
      ru: 'Вычисляйте количество дней, недель, месяцев и лет между двумя датами.',
      ja: '2つの日付の間の日数、週数、月数、年数を計算します。',
    },
    metaTitles: {
      en: 'Date Difference Calculator – Days Between Two Dates',
      ar: 'حاسبة الفرق بين التاريخين – الأيام بين تاريخين',
      fr: 'Calculatrice de Différence de Dates – Jours Entre Deux Dates',
      es: 'Calculadora de Diferencia de Fechas – Días Entre Dos Fechas',
      de: 'Datumsunterschiedrechner – Tage Zwischen Zwei Daten',
      zh: '日期差计算器 – 两个日期之间的天数',
      hi: 'तिथि अंतर कैलकुलेटर – दो तिथियों के बीच के दिन',
      pt: 'Calculadora de Diferença de Datas – Dias Entre Duas Datas',
      ru: 'Калькулятор Разницы Дат – Дни Между Двумя Датами',
      ja: '日付差計算機 – 2つの日付の間の日数',
    },
    metaDescriptions: {
      en: 'Calculate the exact number of days, weeks, months, and years between any two dates.',
      ar: 'احسب العدد الدقيق للأيام والأسابيع والأشهر والسنوات بين أي تاريخين.',
      fr: 'Calculez le nombre exact de jours, semaines, mois et années entre deux dates.',
      es: 'Calcula el número exacto de días, semanas, meses y años entre cualquier par de fechas.',
      de: 'Berechnen Sie die genaue Anzahl von Tagen, Wochen, Monaten und Jahren zwischen zwei Daten.',
      zh: '计算任意两个日期之间的确切天数、周数、月数和年数。',
      hi: 'किसी भी दो तिथियों के बीच दिनों, सप्ताहों, महीनों और वर्षों की सटीक संख्या की गणना करें।',
      pt: 'Calcule o número exato de dias, semanas, meses e anos entre quaisquer duas datas.',
      ru: 'Вычислите точное количество дней, недель, месяцев и лет между двумя датами.',
      ja: '任意の2つの日付の間の正確な日数、週数、月数、年数を計算します。',
    },
    keywords: {
      en: ['date difference', 'days between dates', 'date calculator'],
      ar: ['الفرق بين تاريخين', 'أيام بين تاريخين'],
      fr: ['différence de dates', 'jours entre dates'],
      es: ['diferencia fechas', 'días entre fechas'],
      de: ['Datumsunterschied', 'Tage zwischen Daten'],
      zh: ['日期差', '两个日期之间的天数'],
      hi: ['तिथि अंतर', 'तिथियों के बीच दिन'],
      pt: ['diferença datas', 'dias entre datas'],
      ru: ['разница дат', 'дни между датами'],
      ja: ['日付差', '日付間の日数'],
    },
  },
  // ===== FINANCE =====
  {
    id: 'loan',
    slug: 'loan-calculator',
    categoryId: 'finance',
    icon: '🏦',
    isPopular: true,
    names: {
      en: 'Loan Calculator',
      ar: 'حاسبة القروض',
      fr: 'Calculatrice de Prêt',
      es: 'Calculadora de Préstamos',
      de: 'Kreditrechner',
      zh: '贷款计算器',
      hi: 'ऋण कैलकुलेटर',
      pt: 'Calculadora de Empréstimos',
      ru: 'Кредитный Калькулятор',
      ja: 'ローン計算機',
    },
    descriptions: {
      en: 'Calculate monthly loan payments, total interest, and amortization schedule.',
      ar: 'احسب أقساط القرض الشهرية وإجمالي الفائدة وجدول الاستهلاك.',
      fr: 'Calculez les mensualités de prêt, l\'intérêt total et le tableau d\'amortissement.',
      es: 'Calcula pagos mensuales de préstamos, interés total y cronograma de amortización.',
      de: 'Berechnen Sie monatliche Kreditraten, Gesamtzinsen und Tilgungsplan.',
      zh: '计算每月贷款还款额、总利息和摊销计划。',
      hi: 'मासिक ऋण भुगतान, कुल ब्याज और परिशोधन अनुसूची की गणना करें।',
      pt: 'Calcule pagamentos mensais de empréstimos, juros totais e cronograma de amortização.',
      ru: 'Вычисляйте ежемесячные платежи по кредиту, общую сумму процентов и график погашения.',
      ja: '月々のローン返済額、総利息、返済スケジュールを計算します。',
    },
    metaTitles: {
      en: 'Loan Calculator – Calculate Monthly Payments & Total Interest',
      ar: 'حاسبة القروض – احسب الأقساط الشهرية وإجمالي الفائدة',
      fr: 'Calculatrice de Prêt – Calculez les Mensualités et l\'Intérêt Total',
      es: 'Calculadora de Préstamos – Calcula Pagos Mensuales e Interés Total',
      de: 'Kreditrechner – Monatliche Raten und Gesamtzinsen Berechnen',
      zh: '贷款计算器 – 计算每月还款和总利息',
      hi: 'ऋण कैलकुलेटर – मासिक भुगतान और कुल ब्याज की गणना करें',
      pt: 'Calculadora de Empréstimos – Calcule Pagamentos Mensais e Juros Totais',
      ru: 'Кредитный Калькулятор – Рассчитайте Ежемесячные Платежи и Общую Сумму Процентов',
      ja: 'ローン計算機 – 月々の返済額と総利息を計算',
    },
    metaDescriptions: {
      en: 'Free online loan calculator. Compute monthly payments, total interest cost, and view amortization schedule.',
      ar: 'حاسبة القروض المجانية. احسب الأقساط الشهرية وإجمالي تكلفة الفائدة.',
      fr: 'Calculatrice de prêt gratuite. Calculez les mensualités, le coût total des intérêts.',
      es: 'Calculadora de préstamos gratuita. Calcula pagos mensuales, costo total de intereses.',
      de: 'Kostenloser Kreditrechner. Berechnen Sie monatliche Raten und Gesamtzinskosten.',
      zh: '免费在线贷款计算器。计算月还款额、总利息成本，查看摊销计划。',
      hi: 'मुफ्त ऑनलाइन ऋण कैलकुलेटर। मासिक भुगतान, कुल ब्याज लागत की गणना करें।',
      pt: 'Calculadora de empréstimos gratuita. Calcule pagamentos mensais e custo total de juros.',
      ru: 'Бесплатный кредитный калькулятор. Рассчитайте ежемесячные платежи и общую стоимость процентов.',
      ja: '無料のオンラインローン計算機。月々の返済額と総利息コストを計算します。',
    },
    keywords: {
      en: ['loan calculator', 'monthly payment calculator', 'interest calculator'],
      ar: ['حاسبة قروض', 'قسط شهري'],
      fr: ['calculatrice prêt', 'mensualité crédit'],
      es: ['calculadora préstamos', 'cuota mensual'],
      de: ['Kreditrechner', 'monatliche Rate'],
      zh: ['贷款计算器', '月还款额'],
      hi: ['ऋण कैलकुलेटर', 'मासिक किस्त'],
      pt: ['calculadora empréstimo', 'parcela mensal'],
      ru: ['кредитный калькулятор', 'ежемесячный платёж'],
      ja: ['ローン計算機', '月々の返済額'],
    },
  },
  {
    id: 'compound-interest',
    slug: 'compound-interest-calculator',
    categoryId: 'finance',
    icon: '📈',
    isNew: true,
    names: {
      en: 'Compound Interest Calculator',
      ar: 'حاسبة الفائدة المركبة',
      fr: 'Calculatrice d\'Intérêt Composé',
      es: 'Calculadora de Interés Compuesto',
      de: 'Zinseszinsrechner',
      zh: '复利计算器',
      hi: 'चक्रवृद्धि ब्याज कैलकुलेटर',
      pt: 'Calculadora de Juros Compostos',
      ru: 'Калькулятор Сложных Процентов',
      ja: '複利計算機',
    },
    descriptions: {
      en: 'Calculate compound interest growth over time with different compounding periods.',
      ar: 'احسب نمو الفائدة المركبة مع مرور الوقت مع فترات مركبة مختلفة.',
      fr: 'Calculez la croissance des intérêts composés dans le temps avec différentes périodes de capitalisation.',
      es: 'Calcula el crecimiento del interés compuesto a lo largo del tiempo con diferentes períodos de capitalización.',
      de: 'Berechnen Sie das Zinseszinswachstum im Laufe der Zeit mit verschiedenen Zinsperioden.',
      zh: '计算不同复利周期下的复利增长。',
      hi: 'विभिन्न चक्रवृद्धि अवधियों के साथ समय के साथ चक्रवृद्धि ब्याज वृद्धि की गणना करें।',
      pt: 'Calcule o crescimento de juros compostos ao longo do tempo com diferentes períodos de capitalização.',
      ru: 'Вычисляйте рост сложных процентов во времени с разными периодами начисления.',
      ja: '異なる複利期間での複利の成長を計算します。',
    },
    metaTitles: {
      en: 'Compound Interest Calculator – Investment Growth Over Time',
      ar: 'حاسبة الفائدة المركبة – نمو الاستثمار مع مرور الوقت',
      fr: 'Calculatrice d\'Intérêt Composé – Croissance des Investissements',
      es: 'Calculadora de Interés Compuesto – Crecimiento de Inversiones',
      de: 'Zinseszinsrechner – Investitionswachstum im Zeitverlauf',
      zh: '复利计算器 – 投资随时间增长',
      hi: 'चक्रवृद्धि ब्याज कैलकुलेटर – समय के साथ निवेश वृद्धि',
      pt: 'Calculadora de Juros Compostos – Crescimento de Investimentos',
      ru: 'Калькулятор Сложных Процентов – Рост Инвестиций с Течением Времени',
      ja: '複利計算機 – 時間をかけた投資成長',
    },
    metaDescriptions: {
      en: 'Free compound interest calculator. See how your investment grows over time with compound interest.',
      ar: 'حاسبة الفائدة المركبة المجانية. انظر كيف ينمو استثمارك مع مرور الوقت.',
      fr: 'Calculatrice d\'intérêt composé gratuite. Voyez comment votre investissement croît avec le temps.',
      es: 'Calculadora de interés compuesto gratuita. Ve cómo crece tu inversión con el tiempo.',
      de: 'Kostenloser Zinseszinsrechner. Sehen Sie, wie Ihre Investition im Laufe der Zeit wächst.',
      zh: '免费复利计算器。了解您的投资如何随时间复利增长。',
      hi: 'मुफ्त चक्रवृद्धि ब्याज कैलकुलेटर। देखें कि आपका निवेश समय के साथ कैसे बढ़ता है।',
      pt: 'Calculadora de juros compostos gratuita. Veja como seu investimento cresce com o tempo.',
      ru: 'Бесплатный калькулятор сложных процентов. Посмотрите, как растёт ваша инвестиция.',
      ja: '無料の複利計算機。時間をかけて投資がどのように成長するかを確認します。',
    },
    keywords: {
      en: ['compound interest', 'investment calculator', 'interest growth'],
      ar: ['فائدة مركبة', 'نمو استثمار'],
      fr: ['intérêt composé', 'croissance investissement'],
      es: ['interés compuesto', 'crecimiento inversión'],
      de: ['Zinseszins', 'Investitionswachstum'],
      zh: ['复利', '投资增长'],
      hi: ['चक्रवृद्धि ब्याज', 'निवेश वृद्धि'],
      pt: ['juros compostos', 'crescimento investimento'],
      ru: ['сложные проценты', 'рост инвестиций'],
      ja: ['複利', '投資成長'],
    },
  },
  {
    id: 'currency',
    slug: 'currency-converter',
    categoryId: 'finance',
    icon: '💱',
    isPopular: true,
    names: {
      en: 'Currency Converter',
      ar: 'محول العملات',
      fr: 'Convertisseur de Devises',
      es: 'Convertidor de Divisas',
      de: 'Währungsrechner',
      zh: '货币转换器',
      hi: 'मुद्रा परिवर्तक',
      pt: 'Conversor de Moedas',
      ru: 'Конвертер Валют',
      ja: '通貨コンバーター',
    },
    descriptions: {
      en: 'Convert between world currencies with up-to-date exchange rates.',
      ar: 'تحويل بين عملات العالم بأسعار صرف محدثة.',
      fr: 'Convertissez entre les devises mondiales avec des taux de change à jour.',
      es: 'Convierte entre divisas mundiales con tasas de cambio actualizadas.',
      de: 'Konvertieren Sie zwischen Weltwährungen mit aktuellen Wechselkursen.',
      zh: '使用最新汇率在世界货币之间进行转换。',
      hi: 'अद्यतन विनिमय दरों के साथ विश्व मुद्राओं के बीच परिवर्तित करें।',
      pt: 'Converta entre moedas mundiais com taxas de câmbio atualizadas.',
      ru: 'Конвертируйте между мировыми валютами с актуальными курсами обмена.',
      ja: '最新の為替レートで世界通貨間の変換を行います。',
    },
    metaTitles: {
      en: 'Currency Converter – Convert World Currencies',
      ar: 'محول العملات – تحويل عملات العالم',
      fr: 'Convertisseur de Devises – Convertir les Devises Mondiales',
      es: 'Convertidor de Divisas – Convertir Monedas Mundiales',
      de: 'Währungsrechner – Weltwährungen Umrechnen',
      zh: '货币转换器 – 转换世界货币',
      hi: 'मुद्रा परिवर्तक – विश्व मुद्राएं परिवर्तित करें',
      pt: 'Conversor de Moedas – Converter Moedas Mundiais',
      ru: 'Конвертер Валют – Конвертируйте Мировые Валюты',
      ja: '通貨コンバーター – 世界通貨を変換',
    },
    metaDescriptions: {
      en: 'Free online currency converter. Convert between hundreds of world currencies with live exchange rates.',
      ar: 'محول عملات مجاني. تحويل بين مئات العملات العالمية بأسعار صرف حية.',
      fr: 'Convertisseur de devises gratuit. Convertissez entre des centaines de devises mondiales.',
      es: 'Convertidor de divisas gratuito. Convierte entre cientos de divisas mundiales.',
      de: 'Kostenloser Währungsrechner. Konvertieren Sie zwischen Hunderten von Weltwährungen.',
      zh: '免费在线货币转换器。使用实时汇率在数百种世界货币之间进行转换。',
      hi: 'मुफ्त ऑनलाइन मुद्रा परिवर्तक। लाइव विनिमय दरों के साथ सैकड़ों विश्व मुद्राओं के बीच परिवर्तित करें।',
      pt: 'Conversor de moedas gratuito. Converta entre centenas de moedas mundiais.',
      ru: 'Бесплатный конвертер валют. Конвертируйте между сотнями мировых валют с живыми курсами.',
      ja: '無料のオンライン通貨コンバーター。ライブ為替レートで数百の世界通貨間の変換。',
    },
    keywords: {
      en: ['currency converter', 'exchange rate', 'forex calculator'],
      ar: ['محول عملات', 'سعر الصرف', 'تحويل عملة'],
      fr: ['convertisseur devises', 'taux de change'],
      es: ['convertidor divisas', 'tipo de cambio'],
      de: ['Währungsrechner', 'Wechselkurs'],
      zh: ['货币转换器', '汇率'],
      hi: ['मुद्रा परिवर्तक', 'विनिमय दर'],
      pt: ['conversor moedas', 'taxa de câmbio'],
      ru: ['конвертер валют', 'курс обмена'],
      ja: ['通貨コンバーター', '為替レート'],
    },
  },
  // ===== HEALTH =====
  {
    id: 'bmi',
    slug: 'bmi-calculator',
    categoryId: 'health',
    icon: '⚖️',
    isPopular: true,
    names: {
      en: 'BMI Calculator',
      ar: 'حاسبة مؤشر كتلة الجسم',
      fr: 'Calculatrice IMC',
      es: 'Calculadora IMC',
      de: 'BMI-Rechner',
      zh: 'BMI计算器',
      hi: 'BMI कैलकुलेटर',
      pt: 'Calculadora IMC',
      ru: 'Калькулятор ИМТ',
      ja: 'BMI計算機',
    },
    descriptions: {
      en: 'Calculate your Body Mass Index (BMI) and find out if you\'re at a healthy weight.',
      ar: 'احسب مؤشر كتلة جسمك (BMI) واعرف ما إذا كنت في وزن صحي.',
      fr: 'Calculez votre Indice de Masse Corporelle (IMC) et découvrez si vous êtes à un poids sain.',
      es: 'Calcula tu Índice de Masa Corporal (IMC) y descubre si tienes un peso saludable.',
      de: 'Berechnen Sie Ihren Body-Mass-Index (BMI) und finden Sie heraus, ob Sie ein gesundes Gewicht haben.',
      zh: '计算您的体质指数（BMI），了解您是否处于健康体重。',
      hi: 'अपना बॉडी मास इंडेक्स (BMI) की गणना करें और जानें कि आप स्वस्थ वजन पर हैं या नहीं।',
      pt: 'Calcule seu Índice de Massa Corporal (IMC) e descubra se está em um peso saudável.',
      ru: 'Вычислите свой индекс массы тела (ИМТ) и узнайте, является ли ваш вес здоровым.',
      ja: '体格指数（BMI）を計算し、健康的な体重かどうかを確認します。',
    },
    metaTitles: {
      en: 'BMI Calculator – Body Mass Index Calculator',
      ar: 'حاسبة مؤشر كتلة الجسم BMI',
      fr: 'Calculatrice IMC – Indice de Masse Corporelle',
      es: 'Calculadora IMC – Índice de Masa Corporal',
      de: 'BMI-Rechner – Body-Mass-Index Berechnen',
      zh: 'BMI计算器 – 体质指数计算器',
      hi: 'BMI कैलकुलेटर – बॉडी मास इंडेक्स',
      pt: 'Calculadora IMC – Índice de Massa Corporal',
      ru: 'Калькулятор ИМТ – Индекс Массы Тела',
      ja: 'BMI計算機 – 体格指数計算機',
    },
    metaDescriptions: {
      en: 'Free BMI calculator. Calculate your body mass index and understand your weight status according to WHO standards.',
      ar: 'حاسبة مؤشر كتلة الجسم المجانية. احسب مؤشر كتلة جسمك وافهم وضع وزنك.',
      fr: 'Calculatrice IMC gratuite. Calculez votre indice de masse corporelle et comprenez votre statut de poids.',
      es: 'Calculadora IMC gratuita. Calcula tu índice de masa corporal y comprende tu estado de peso.',
      de: 'Kostenloser BMI-Rechner. Berechnen Sie Ihren Body-Mass-Index und verstehen Sie Ihren Gewichtsstatus.',
      zh: '免费BMI计算器。计算您的体质指数，了解您的体重状况。',
      hi: 'मुफ्त BMI कैलकुलेटर। अपना बॉडी मास इंडेक्स गणना करें और वजन स्थिति समझें।',
      pt: 'Calculadora IMC gratuita. Calcule seu índice de massa corporal e entenda seu status de peso.',
      ru: 'Бесплатный калькулятор ИМТ. Вычислите индекс массы тела и поймите свой весовой статус.',
      ja: '無料のBMI計算機。体格指数を計算し、体重状態を理解します。',
    },
    keywords: {
      en: ['bmi calculator', 'body mass index', 'healthy weight'],
      ar: ['حاسبة BMI', 'مؤشر كتلة الجسم', 'الوزن الصحي'],
      fr: ['calculatrice IMC', 'indice masse corporelle'],
      es: ['calculadora IMC', 'índice masa corporal'],
      de: ['BMI-Rechner', 'Body-Mass-Index'],
      zh: ['BMI计算器', '体质指数'],
      hi: ['BMI कैलकुलेटर', 'बॉडी मास इंडेक्स'],
      pt: ['calculadora IMC', 'índice massa corporal'],
      ru: ['калькулятор ИМТ', 'индекс массы тела'],
      ja: ['BMI計算機', '体格指数'],
    },
  },
  {
    id: 'calorie',
    slug: 'calorie-calculator',
    categoryId: 'health',
    icon: '🔥',
    isNew: true,
    names: {
      en: 'Calorie Calculator',
      ar: 'حاسبة السعرات الحرارية',
      fr: 'Calculatrice de Calories',
      es: 'Calculadora de Calorías',
      de: 'Kalorienrechner',
      zh: '卡路里计算器',
      hi: 'कैलोरी कैलकुलेटर',
      pt: 'Calculadora de Calorias',
      ru: 'Калькулятор Калорий',
      ja: 'カロリー計算機',
    },
    descriptions: {
      en: 'Calculate your daily calorie needs based on age, weight, height, and activity level.',
      ar: 'احسب احتياجاتك اليومية من السعرات الحرارية بناءً على العمر والوزن والطول ومستوى النشاط.',
      fr: 'Calculez vos besoins caloriques quotidiens en fonction de l\'âge, du poids, de la taille et du niveau d\'activité.',
      es: 'Calcula tus necesidades calóricas diarias según edad, peso, altura y nivel de actividad.',
      de: 'Berechnen Sie Ihren täglichen Kalorienbedarf basierend auf Alter, Gewicht, Größe und Aktivitätsniveau.',
      zh: '根据年龄、体重、身高和活动水平计算每日卡路里需求。',
      hi: 'आयु, वजन, ऊंचाई और गतिविधि स्तर के आधार पर अपनी दैनिक कैलोरी आवश्यकताओं की गणना करें।',
      pt: 'Calcule suas necessidades calóricas diárias com base em idade, peso, altura e nível de atividade.',
      ru: 'Рассчитайте суточную потребность в калориях на основе возраста, веса, роста и уровня активности.',
      ja: '年齢、体重、身長、活動レベルに基づいて1日のカロリー必要量を計算します。',
    },
    metaTitles: {
      en: 'Calorie Calculator – Daily Calorie Needs & TDEE',
      ar: 'حاسبة السعرات الحرارية – الاحتياجات اليومية من السعرات الحرارية',
      fr: 'Calculatrice de Calories – Besoins Caloriques Quotidiens',
      es: 'Calculadora de Calorías – Necesidades Calóricas Diarias',
      de: 'Kalorienrechner – Täglicher Kalorienbedarf',
      zh: '卡路里计算器 – 每日卡路里需求',
      hi: 'कैलोरी कैलकुलेटर – दैनिक कैलोरी आवश्यकताएं',
      pt: 'Calculadora de Calorias – Necessidades Calóricas Diárias',
      ru: 'Калькулятор Калорий – Суточная Потребность в Калориях',
      ja: 'カロリー計算機 – 1日のカロリー必要量',
    },
    metaDescriptions: {
      en: 'Free calorie calculator. Find your daily calorie needs (TDEE) for weight loss, maintenance, or gain.',
      ar: 'حاسبة السعرات الحرارية المجانية. اعثر على احتياجاتك اليومية من السعرات الحرارية.',
      fr: 'Calculatrice de calories gratuite. Trouvez vos besoins caloriques quotidiens.',
      es: 'Calculadora de calorías gratuita. Encuentra tus necesidades calóricas diarias.',
      de: 'Kostenloser Kalorienrechner. Finden Sie Ihren täglichen Kalorienbedarf.',
      zh: '免费卡路里计算器。找出您的每日卡路里需求（TDEE）。',
      hi: 'मुफ्त कैलोरी कैलकुलेटर। वजन घटाने, रखरखाव या बढ़ाने के लिए दैनिक कैलोरी आवश्यकता जानें।',
      pt: 'Calculadora de calorias gratuita. Encontre suas necessidades calóricas diárias.',
      ru: 'Бесплатный калькулятор калорий. Найдите суточную потребность в калориях.',
      ja: '無料のカロリー計算機。体重減少、維持、増量のための1日のカロリー必要量を求めます。',
    },
    keywords: {
      en: ['calorie calculator', 'TDEE calculator', 'daily calories'],
      ar: ['حاسبة سعرات حرارية', 'السعرات الحرارية اليومية'],
      fr: ['calculatrice calories', 'besoins caloriques'],
      es: ['calculadora calorías', 'calorías diarias'],
      de: ['Kalorienrechner', 'Tageskalorienbedarf'],
      zh: ['卡路里计算器', '每日卡路里'],
      hi: ['कैलोरी कैलकुलेटर', 'दैनिक कैलोरी'],
      pt: ['calculadora calorias', 'calorias diárias'],
      ru: ['калькулятор калорий', 'дневные калории'],
      ja: ['カロリー計算機', '1日のカロリー'],
    },
  },
  // ===== CONVERTERS =====
  {
    id: 'length',
    slug: 'length-converter',
    categoryId: 'converters',
    icon: '📐',
    isPopular: true,
    names: {
      en: 'Length Converter',
      ar: 'محول الطول',
      fr: 'Convertisseur de Longueur',
      es: 'Conversor de Longitud',
      de: 'Längenkonverter',
      zh: '长度转换器',
      hi: 'लंबाई परिवर्तक',
      pt: 'Conversor de Comprimento',
      ru: 'Конвертер Длины',
      ja: '長さコンバーター',
    },
    descriptions: {
      en: 'Convert between meters, feet, inches, centimeters, kilometers, miles, and more.',
      ar: 'تحويل بين الأمتار والأقدام والبوصات والسنتيمترات والكيلومترات والأميال والمزيد.',
      fr: 'Convertissez entre mètres, pieds, pouces, centimètres, kilomètres, miles et plus.',
      es: 'Convierte entre metros, pies, pulgadas, centímetros, kilómetros, millas y más.',
      de: 'Konvertieren Sie zwischen Metern, Fuß, Zoll, Zentimetern, Kilometern, Meilen und mehr.',
      zh: '在米、英尺、英寸、厘米、公里、英里等之间转换。',
      hi: 'मीटर, फीट, इंच, सेंटीमीटर, किलोमीटर, मील और अधिक के बीच परिवर्तित करें।',
      pt: 'Converta entre metros, pés, polegadas, centímetros, quilômetros, milhas e mais.',
      ru: 'Конвертируйте между метрами, футами, дюймами, сантиметрами, километрами, милями и многим другим.',
      ja: 'メートル、フィート、インチ、センチメートル、キロメートル、マイルなどの間で変換します。',
    },
    metaTitles: {
      en: 'Length Converter – Convert Meters, Feet, Inches & More',
      ar: 'محول الطول – تحويل الأمتار والأقدام والبوصات',
      fr: 'Convertisseur de Longueur – Convertir Mètres, Pieds, Pouces',
      es: 'Conversor de Longitud – Convertir Metros, Pies, Pulgadas',
      de: 'Längenkonverter – Meter, Fuß, Zoll Umrechnen',
      zh: '长度转换器 – 转换米、英尺、英寸等',
      hi: 'लंबाई परिवर्तक – मीटर, फीट, इंच परिवर्तित करें',
      pt: 'Conversor de Comprimento – Converter Metros, Pés, Polegadas',
      ru: 'Конвертер Длины – Конвертировать Метры, Футы, Дюймы',
      ja: '長さコンバーター – メートル、フィート、インチを変換',
    },
    metaDescriptions: {
      en: 'Free length converter. Convert between all units of length including metric and imperial units.',
      ar: 'محول الطول المجاني. تحويل بين جميع وحدات الطول بما في ذلك الوحدات المترية والإمبراطورية.',
      fr: 'Convertisseur de longueur gratuit. Convertissez entre toutes les unités de longueur.',
      es: 'Conversor de longitud gratuito. Convierte entre todas las unidades de longitud.',
      de: 'Kostenloser Längenkonverter. Konvertieren Sie zwischen allen Längeneinheiten.',
      zh: '免费长度转换器。在所有长度单位之间进行转换。',
      hi: 'मुफ्त लंबाई परिवर्तक। मीट्रिक और शाही इकाइयों सहित सभी लंबाई इकाइयों के बीच परिवर्तित करें।',
      pt: 'Conversor de comprimento gratuito. Converta entre todas as unidades de comprimento.',
      ru: 'Бесплатный конвертер длины. Конвертируйте между всеми единицами длины.',
      ja: '無料の長さコンバーター。メートル法と帝国単位を含むすべての長さの単位を変換します。',
    },
    keywords: {
      en: ['length converter', 'meters to feet', 'unit converter', 'cm to inches'],
      ar: ['محول طول', 'أمتار إلى أقدام', 'تحويل وحدات'],
      fr: ['convertisseur longueur', 'mètres en pieds'],
      es: ['conversor longitud', 'metros a pies'],
      de: ['Längenkonverter', 'Meter in Fuß'],
      zh: ['长度转换器', '米转英尺'],
      hi: ['लंबाई परिवर्तक', 'मीटर से फीट'],
      pt: ['conversor comprimento', 'metros para pés'],
      ru: ['конвертер длины', 'метры в футы'],
      ja: ['長さコンバーター', 'メートルをフィートに'],
    },
  },
  {
    id: 'temperature',
    slug: 'temperature-converter',
    categoryId: 'converters',
    icon: '🌡️',
    names: {
      en: 'Temperature Converter',
      ar: 'محول درجة الحرارة',
      fr: 'Convertisseur de Température',
      es: 'Conversor de Temperatura',
      de: 'Temperaturkonverter',
      zh: '温度转换器',
      hi: 'तापमान परिवर्तक',
      pt: 'Conversor de Temperatura',
      ru: 'Конвертер Температуры',
      ja: '温度コンバーター',
    },
    descriptions: {
      en: 'Convert between Celsius, Fahrenheit, Kelvin, and Rankine temperature scales.',
      ar: 'تحويل بين مقاييس درجة الحرارة: سيلسيوس وفهرنهايت وكلفن وراونكين.',
      fr: 'Convertissez entre les échelles de température Celsius, Fahrenheit, Kelvin et Rankine.',
      es: 'Convierte entre las escalas de temperatura Celsius, Fahrenheit, Kelvin y Rankine.',
      de: 'Konvertieren Sie zwischen Celsius, Fahrenheit, Kelvin und Rankine-Temperaturskalen.',
      zh: '在摄氏度、华氏度、开尔文和兰金温度刻度之间转换。',
      hi: 'सेल्सियस, फ़ारेनहाइट, केल्विन और रैंकिन तापमान पैमाने के बीच परिवर्तित करें।',
      pt: 'Converta entre as escalas de temperatura Celsius, Fahrenheit, Kelvin e Rankine.',
      ru: 'Конвертируйте между шкалами температур Цельсий, Фаренгейт, Кельвин и Ранкин.',
      ja: '摂氏、華氏、ケルビン、ランキンの温度スケールを変換します。',
    },
    metaTitles: {
      en: 'Temperature Converter – Celsius to Fahrenheit & More',
      ar: 'محول درجة الحرارة – سيلسيوس إلى فهرنهايت',
      fr: 'Convertisseur de Température – Celsius en Fahrenheit',
      es: 'Conversor de Temperatura – Celsius a Fahrenheit',
      de: 'Temperaturkonverter – Celsius in Fahrenheit',
      zh: '温度转换器 – 摄氏度转华氏度',
      hi: 'तापमान परिवर्तक – सेल्सियस से फ़ारेनहाइट',
      pt: 'Conversor de Temperatura – Celsius para Fahrenheit',
      ru: 'Конвертер Температуры – Цельсий в Фаренгейт',
      ja: '温度コンバーター – 摂氏から華氏へ',
    },
    metaDescriptions: {
      en: 'Free temperature converter. Convert between Celsius, Fahrenheit, Kelvin instantly.',
      ar: 'محول درجة الحرارة المجاني. تحويل بين سيلسيوس وفهرنهايت وكلفن فورًا.',
      fr: 'Convertisseur de température gratuit. Convertissez entre Celsius, Fahrenheit, Kelvin instantanément.',
      es: 'Conversor de temperatura gratuito. Convierte entre Celsius, Fahrenheit, Kelvin al instante.',
      de: 'Kostenloser Temperaturkonverter. Konvertieren Sie sofort zwischen Celsius, Fahrenheit, Kelvin.',
      zh: '免费温度转换器。即时在摄氏度、华氏度、开尔文之间转换。',
      hi: 'मुफ्त तापमान परिवर्तक। सेल्सियस, फ़ारेनहाइट, केल्विन के बीच तुरंत परिवर्तित करें।',
      pt: 'Conversor de temperatura gratuito. Converta instantaneamente entre Celsius, Fahrenheit, Kelvin.',
      ru: 'Бесплатный конвертер температур. Мгновенно конвертируйте между Цельсием, Фаренгейтом, Кельвином.',
      ja: '無料の温度コンバーター。摂氏、華氏、ケルビンを即座に変換します。',
    },
    keywords: {
      en: ['temperature converter', 'celsius to fahrenheit', 'fahrenheit to celsius'],
      ar: ['محول درجة حرارة', 'سيلسيوس إلى فهرنهايت'],
      fr: ['convertisseur température', 'celsius en fahrenheit'],
      es: ['conversor temperatura', 'celsius a fahrenheit'],
      de: ['Temperaturkonverter', 'Celsius in Fahrenheit'],
      zh: ['温度转换器', '摄氏度转华氏度'],
      hi: ['तापमान परिवर्तक', 'सेल्सियस से फ़ारेनहाइट'],
      pt: ['conversor temperatura', 'celsius para fahrenheit'],
      ru: ['конвертер температур', 'цельсий в фаренгейт'],
      ja: ['温度コンバーター', '摂氏から華氏'],
    },
  },
  {
    id: 'weight',
    slug: 'weight-converter',
    categoryId: 'converters',
    icon: '⚖️',
    names: {
      en: 'Weight Converter',
      ar: 'محول الوزن',
      fr: 'Convertisseur de Poids',
      es: 'Conversor de Peso',
      de: 'Gewichtskonverter',
      zh: '重量转换器',
      hi: 'वजन परिवर्तक',
      pt: 'Conversor de Peso',
      ru: 'Конвертер Веса',
      ja: '重さコンバーター',
    },
    descriptions: {
      en: 'Convert between kilograms, pounds, ounces, grams, tons, and all weight units.',
      ar: 'تحويل بين الكيلوغرامات والأرطال والأونصات والجرامات والأطنان وجميع وحدات الوزن.',
      fr: 'Convertissez entre kilogrammes, livres, onces, grammes, tonnes et toutes les unités de poids.',
      es: 'Convierte entre kilogramos, libras, onzas, gramos, toneladas y todas las unidades de peso.',
      de: 'Konvertieren Sie zwischen Kilogramm, Pfund, Unzen, Gramm, Tonnen und allen Gewichtseinheiten.',
      zh: '在千克、磅、盎司、克、吨和所有重量单位之间转换。',
      hi: 'किलोग्राम, पाउंड, औंस, ग्राम, टन और सभी वजन इकाइयों के बीच परिवर्तित करें।',
      pt: 'Converta entre quilogramas, libras, onças, gramas, toneladas e todas as unidades de peso.',
      ru: 'Конвертируйте между килограммами, фунтами, унциями, граммами, тоннами и всеми единицами веса.',
      ja: 'キログラム、ポンド、オンス、グラム、トンなどすべての重量単位を変換します。',
    },
    metaTitles: {
      en: 'Weight Converter – Convert kg, lbs, Pounds & Grams',
      ar: 'محول الوزن – تحويل كيلوجرام وباوند وجرام',
      fr: 'Convertisseur de Poids – Convertir kg, livres, grammes',
      es: 'Conversor de Peso – Convertir kg, libras, gramos',
      de: 'Gewichtskonverter – kg, Pfund, Gramm Umrechnen',
      zh: '重量转换器 – 转换千克、磅、克',
      hi: 'वजन परिवर्तक – किग्रा, पाउंड, ग्राम परिवर्तित करें',
      pt: 'Conversor de Peso – Converter kg, libras, gramas',
      ru: 'Конвертер Веса – Конвертировать кг, фунты, граммы',
      ja: '重さコンバーター – kg、ポンド、グラムを変換',
    },
    metaDescriptions: {
      en: 'Free weight converter. Convert between kilograms, pounds, ounces, and all weight units instantly.',
      ar: 'محول الوزن المجاني. تحويل بين الكيلوغرامات والأرطال والأونصات فورًا.',
      fr: 'Convertisseur de poids gratuit. Convertissez entre kilogrammes, livres et onces instantanément.',
      es: 'Conversor de peso gratuito. Convierte entre kilogramos, libras y onzas al instante.',
      de: 'Kostenloser Gewichtskonverter. Konvertieren Sie sofort zwischen Kilogramm, Pfund und Unzen.',
      zh: '免费重量转换器。即时在千克、磅、盎司之间转换。',
      hi: 'मुफ्त वजन परिवर्तक। किलोग्राम, पाउंड, औंस के बीच तुरंत परिवर्तित करें।',
      pt: 'Conversor de peso gratuito. Converta instantaneamente entre quilogramas, libras e onças.',
      ru: 'Бесплатный конвертер веса. Мгновенно конвертируйте между килограммами, фунтами и унциями.',
      ja: '無料の重さコンバーター。キログラム、ポンド、オンスを即座に変換します。',
    },
    keywords: {
      en: ['weight converter', 'kg to lbs', 'pounds to kg', 'unit converter'],
      ar: ['محول وزن', 'كيلو إلى رطل', 'تحويل وزن'],
      fr: ['convertisseur poids', 'kg en livres'],
      es: ['conversor peso', 'kg a libras'],
      de: ['Gewichtskonverter', 'Kilogramm in Pfund'],
      zh: ['重量转换器', '千克转磅'],
      hi: ['वजन परिवर्तक', 'किग्रा से पाउंड'],
      pt: ['conversor peso', 'kg para libras'],
      ru: ['конвертер веса', 'килограммы в фунты'],
      ja: ['重さコンバーター', 'キログラムをポンドに'],
    },
  },
  // ===== TECH =====
  {
    id: 'binary',
    slug: 'binary-converter',
    categoryId: 'tech',
    icon: '01',
    isNew: true,
    names: {
      en: 'Binary Converter',
      ar: 'محول الثنائي',
      fr: 'Convertisseur Binaire',
      es: 'Convertidor Binario',
      de: 'Binärkonverter',
      zh: '二进制转换器',
      hi: 'बाइनरी कनवर्टर',
      pt: 'Conversor Binário',
      ru: 'Конвертер Двоичного Кода',
      ja: '2進数コンバーター',
    },
    descriptions: {
      en: 'Convert between binary, decimal, hexadecimal, and octal number systems.',
      ar: 'تحويل بين الأنظمة الثنائية والعشرية والسداسية عشر والثمانية.',
      fr: 'Convertissez entre les systèmes de nombres binaires, décimaux, hexadécimaux et octaux.',
      es: 'Convierte entre sistemas numéricos binarios, decimales, hexadecimales y octales.',
      de: 'Konvertieren Sie zwischen binären, dezimalen, hexadezimalen und oktalen Zahlensystemen.',
      zh: '在二进制、十进制、十六进制和八进制数字系统之间转换。',
      hi: 'बाइनरी, दशमलव, हेक्साडेसिमल और ऑक्टल नंबर सिस्टम के बीच कनवर्ट करें।',
      pt: 'Converta entre sistemas numéricos binários, decimais, hexadecimais e octais.',
      ru: 'Конвертируйте между двоичными, десятичными, шестнадцатеричными и восьмеричными системами счисления.',
      ja: '2進数、10進数、16進数、8進数の数系を変換します。',
    },
    metaTitles: {
      en: 'Binary Converter – Binary to Decimal, Hex & Octal',
      ar: 'محول الثنائي – تحويل بين الثنائي والعشري والسداسي عشر',
      fr: 'Convertisseur Binaire – Binaire en Décimal, Hex et Octal',
      es: 'Convertidor Binario – Binario a Decimal, Hex y Octal',
      de: 'Binärkonverter – Binär in Dezimal, Hex und Oktal',
      zh: '二进制转换器 – 二进制转十进制、十六进制和八进制',
      hi: 'बाइनरी कनवर्टर – बाइनरी से डेसिमल, हेक्स और ऑक्टल',
      pt: 'Conversor Binário – Binário para Decimal, Hex e Octal',
      ru: 'Конвертер Двоичного Кода – Двоичный в Десятичный, Шестнадцатеричный, Восьмеричный',
      ja: '2進数コンバーター – 2進数から10進数、16進数、8進数へ',
    },
    metaDescriptions: {
      en: 'Free binary converter. Convert between binary, decimal, hexadecimal, and octal number systems instantly.',
      ar: 'محول ثنائي مجاني. تحويل بين الأنظمة الثنائية والعشرية والسداسية عشرية فورًا.',
      fr: 'Convertisseur binaire gratuit. Convertissez instantanément entre les systèmes binaire, décimal et hexadécimal.',
      es: 'Convertidor binario gratuito. Convierte al instante entre sistemas binario, decimal y hexadecimal.',
      de: 'Kostenloser Binärkonverter. Konvertieren Sie sofort zwischen binären, dezimalen und hexadezimalen Systemen.',
      zh: '免费二进制转换器。即时在二进制、十进制和十六进制系统之间转换。',
      hi: 'मुफ्त बाइनरी कनवर्टर। बाइनरी, दशमलव और हेक्साडेसिमल सिस्टम के बीच तुरंत कनवर्ट करें।',
      pt: 'Conversor binário gratuito. Converta instantaneamente entre sistemas binário, decimal e hexadecimal.',
      ru: 'Бесплатный конвертер двоичного кода. Мгновенно конвертируйте между двоичными, десятичными и шестнадцатеричными системами.',
      ja: '無料の2進数コンバーター。2進数、10進数、16進数のシステムを即座に変換します。',
    },
    keywords: {
      en: ['binary converter', 'binary to decimal', 'decimal to binary', 'hex converter'],
      ar: ['محول ثنائي', 'تحويل ثنائي إلى عشري'],
      fr: ['convertisseur binaire', 'binaire en décimal'],
      es: ['convertidor binario', 'binario a decimal'],
      de: ['Binärkonverter', 'Binär in Dezimal'],
      zh: ['二进制转换器', '二进制转十进制'],
      hi: ['बाइनरी कनवर्टर', 'बाइनरी से दशमलव'],
      pt: ['conversor binário', 'binário para decimal'],
      ru: ['конвертер двоичного кода', 'двоичный в десятичный'],
      ja: ['2進数コンバーター', '2進数から10進数'],
    },
  },
  {
    id: 'color',
    slug: 'color-converter',
    categoryId: 'tech',
    icon: '🎨',
    names: {
      en: 'Color Code Converter',
      ar: 'محول كود الألوان',
      fr: 'Convertisseur de Code Couleur',
      es: 'Convertidor de Código de Color',
      de: 'Farbcode-Konverter',
      zh: '颜色代码转换器',
      hi: 'रंग कोड कनवर्टर',
      pt: 'Conversor de Código de Cor',
      ru: 'Конвертер Цветового Кода',
      ja: 'カラーコードコンバーター',
    },
    descriptions: {
      en: 'Convert between HEX, RGB, HSL, HSV color codes and view colors visually.',
      ar: 'تحويل بين رموز الألوان HEX وRGB وHSL وHSV وعرض الألوان بصريًا.',
      fr: 'Convertissez entre les codes couleur HEX, RGB, HSL, HSV et visualisez les couleurs.',
      es: 'Convierte entre códigos de color HEX, RGB, HSL, HSV y visualiza colores.',
      de: 'Konvertieren Sie zwischen HEX-, RGB-, HSL-, HSV-Farbcodes und sehen Sie Farben visuell.',
      zh: '在HEX、RGB、HSL、HSV颜色代码之间转换，并直观查看颜色。',
      hi: 'HEX, RGB, HSL, HSV रंग कोड के बीच कनवर्ट करें और रंगों को दृश्य रूप से देखें।',
      pt: 'Converta entre códigos de cor HEX, RGB, HSL, HSV e visualize cores.',
      ru: 'Конвертируйте между цветовыми кодами HEX, RGB, HSL, HSV и просматривайте цвета визуально.',
      ja: 'HEX、RGB、HSL、HSV カラーコード間で変換し、視覚的に色を確認します。',
    },
    metaTitles: {
      en: 'Color Code Converter – HEX to RGB, HSL & HSV',
      ar: 'محول كود الألوان – HEX إلى RGB وHSL',
      fr: 'Convertisseur de Code Couleur – HEX en RGB, HSL',
      es: 'Convertidor de Código de Color – HEX a RGB, HSL',
      de: 'Farbcode-Konverter – HEX zu RGB, HSL',
      zh: '颜色代码转换器 – HEX转RGB、HSL',
      hi: 'रंग कोड कनवर्टर – HEX से RGB, HSL',
      pt: 'Conversor de Código de Cor – HEX para RGB, HSL',
      ru: 'Конвертер Цветового Кода – HEX в RGB, HSL',
      ja: 'カラーコードコンバーター – HEXからRGB、HSLへ',
    },
    metaDescriptions: {
      en: 'Free color code converter. Convert between HEX, RGB, HSL, and HSV color formats instantly.',
      ar: 'محول كود الألوان المجاني. تحويل بين HEX وRGB وHSL وHSV فورًا.',
      fr: 'Convertisseur de code couleur gratuit. Convertissez instantanément entre HEX, RGB, HSL et HSV.',
      es: 'Convertidor de código de color gratuito. Convierte al instante entre HEX, RGB, HSL y HSV.',
      de: 'Kostenloser Farbcode-Konverter. Konvertieren Sie sofort zwischen HEX, RGB, HSL und HSV.',
      zh: '免费颜色代码转换器。即时在HEX、RGB、HSL和HSV颜色格式之间转换。',
      hi: 'मुफ्त रंग कोड कनवर्टर। HEX, RGB, HSL और HSV रंग प्रारूपों के बीच तुरंत कनवर्ट करें।',
      pt: 'Conversor de código de cor gratuito. Converta instantaneamente entre HEX, RGB, HSL e HSV.',
      ru: 'Бесплатный конвертер цветового кода. Мгновенно конвертируйте между HEX, RGB, HSL и HSV.',
      ja: '無料のカラーコードコンバーター。HEX、RGB、HSL、HSV カラーフォーマットを即座に変換します。',
    },
    keywords: {
      en: ['color converter', 'hex to rgb', 'rgb to hex', 'color code'],
      ar: ['محول ألوان', 'تحويل كود لون'],
      fr: ['convertisseur couleur', 'hex en rgb'],
      es: ['convertidor color', 'hex a rgb'],
      de: ['Farbkonverter', 'Hex zu RGB'],
      zh: ['颜色转换器', 'hex转rgb'],
      hi: ['रंग कनवर्टर', 'hex से rgb'],
      pt: ['conversor cor', 'hex para rgb'],
      ru: ['конвертер цвета', 'hex в rgb'],
      ja: ['カラーコンバーター', 'hexからrgb'],
    },
  },
  // ===== EVERYDAY =====
  {
    id: 'tip',
    slug: 'tip-calculator',
    categoryId: 'everyday',
    icon: '🍽️',
    isPopular: true,
    names: {
      en: 'Tip Calculator',
      ar: 'حاسبة البقشيش',
      fr: 'Calculatrice de Pourboire',
      es: 'Calculadora de Propina',
      de: 'Trinkgeldrechner',
      zh: '小费计算器',
      hi: 'टिप कैलकुलेटर',
      pt: 'Calculadora de Gorjeta',
      ru: 'Калькулятор Чаевых',
      ja: 'チップ計算機',
    },
    descriptions: {
      en: 'Calculate tip amount, total bill, and split the bill among friends easily.',
      ar: 'احسب مبلغ البقشيش وإجمالي الفاتورة وقسّم الفاتورة بين الأصدقاء بسهولة.',
      fr: 'Calculez le montant du pourboire, la note totale et partagez l\'addition entre amis facilement.',
      es: 'Calcula el importe de la propina, la cuenta total y divide la cuenta entre amigos fácilmente.',
      de: 'Berechnen Sie den Trinkgeldbetrag, die Gesamtrechnung und teilen Sie die Rechnung unter Freunden auf.',
      zh: '轻松计算小费金额、总账单，并在朋友之间分摊账单。',
      hi: 'टिप राशि, कुल बिल की गणना करें और दोस्तों के बीच बिल आसानी से विभाजित करें।',
      pt: 'Calcule o valor da gorjeta, conta total e divida a conta entre amigos facilmente.',
      ru: 'Вычисляйте сумму чаевых, общий счёт и легко делите счёт среди друзей.',
      ja: 'チップ金額、合計請求額を計算し、友達と簡単に割り勘できます。',
    },
    metaTitles: {
      en: 'Tip Calculator – Calculate Tip & Split the Bill',
      ar: 'حاسبة البقشيش – احسب البقشيش وقسّم الفاتورة',
      fr: 'Calculatrice de Pourboire – Calculer le Pourboire et Partager l\'Addition',
      es: 'Calculadora de Propina – Calcular Propina y Dividir la Cuenta',
      de: 'Trinkgeldrechner – Trinkgeld Berechnen und Rechnung Aufteilen',
      zh: '小费计算器 – 计算小费并分摊账单',
      hi: 'टिप कैलकुलेटर – टिप गणना करें और बिल विभाजित करें',
      pt: 'Calculadora de Gorjeta – Calcular Gorjeta e Dividir a Conta',
      ru: 'Калькулятор Чаевых – Рассчитать Чаевые и Разделить Счёт',
      ja: 'チップ計算機 – チップを計算して割り勘',
    },
    metaDescriptions: {
      en: 'Free tip calculator. Calculate the perfect tip and split the restaurant bill evenly among friends.',
      ar: 'حاسبة البقشيش المجانية. احسب البقشيش المثالي وقسّم فاتورة المطعم بالتساوي بين الأصدقاء.',
      fr: 'Calculatrice de pourboire gratuite. Calculez le pourboire parfait et partagez la note.',
      es: 'Calculadora de propina gratuita. Calcula la propina perfecta y divide la cuenta del restaurante.',
      de: 'Kostenloser Trinkgeldrechner. Berechnen Sie das perfekte Trinkgeld und teilen Sie die Restaurantrechnung auf.',
      zh: '免费小费计算器。计算完美小费并平均分摊餐厅账单。',
      hi: 'मुफ्त टिप कैलकुलेटर। सही टिप की गणना करें और रेस्तरां बिल को समान रूप से दोस्तों में विभाजित करें।',
      pt: 'Calculadora de gorjeta gratuita. Calcule a gorjeta perfeita e divida a conta do restaurante.',
      ru: 'Бесплатный калькулятор чаевых. Вычислите оптимальные чаевые и разделите счёт поровну.',
      ja: '無料のチップ計算機。完璧なチップを計算し、レストランの請求書を均等に割り勘します。',
    },
    keywords: {
      en: ['tip calculator', 'split bill', 'gratuity calculator', 'restaurant tip'],
      ar: ['حاسبة بقشيش', 'تقسيم فاتورة', 'بقشيش مطعم'],
      fr: ['calculatrice pourboire', 'partager addition'],
      es: ['calculadora propina', 'dividir cuenta'],
      de: ['Trinkgeldrechner', 'Rechnung aufteilen'],
      zh: ['小费计算器', '分摊账单'],
      hi: ['टिप कैलकुलेटर', 'बिल विभाजन'],
      pt: ['calculadora gorjeta', 'dividir conta'],
      ru: ['калькулятор чаевых', 'разделить счёт'],
      ja: ['チップ計算機', '割り勘'],
    },
  },
  {
    id: 'fuel',
    slug: 'fuel-cost-calculator',
    categoryId: 'everyday',
    icon: '⛽',
    names: {
      en: 'Fuel Cost Calculator',
      ar: 'حاسبة تكلفة الوقود',
      fr: 'Calculatrice de Coût du Carburant',
      es: 'Calculadora de Costo de Combustible',
      de: 'Kraftstoffkostenrechner',
      zh: '燃油成本计算器',
      hi: 'ईंधन लागत कैलकुलेटर',
      pt: 'Calculadora de Custo de Combustível',
      ru: 'Калькулятор Стоимости Топлива',
      ja: '燃料費計算機',
    },
    descriptions: {
      en: 'Calculate fuel cost for any trip based on distance, fuel efficiency, and fuel price.',
      ar: 'احسب تكلفة الوقود لأي رحلة بناءً على المسافة وكفاءة الوقود وسعر الوقود.',
      fr: 'Calculez le coût du carburant pour tout trajet en fonction de la distance, de l\'efficacité et du prix.',
      es: 'Calcula el costo de combustible para cualquier viaje según distancia, eficiencia y precio.',
      de: 'Berechnen Sie die Kraftstoffkosten für jede Fahrt basierend auf Entfernung, Kraftstoffeffizienz und Preis.',
      zh: '根据距离、燃油效率和燃油价格计算任何旅途的燃油成本。',
      hi: 'दूरी, ईंधन दक्षता और ईंधन मूल्य के आधार पर किसी भी यात्रा की ईंधन लागत की गणना करें।',
      pt: 'Calcule o custo de combustível para qualquer viagem com base em distância, eficiência e preço.',
      ru: 'Вычисляйте стоимость топлива для любой поездки на основе расстояния, расхода и цены топлива.',
      ja: '距離、燃費、燃料価格に基づいて任意の旅行の燃料費を計算します。',
    },
    metaTitles: {
      en: 'Fuel Cost Calculator – Calculate Trip Fuel Expenses',
      ar: 'حاسبة تكلفة الوقود – احسب نفقات وقود الرحلة',
      fr: 'Calculatrice de Coût du Carburant – Calculer les Frais de Carburant',
      es: 'Calculadora de Costo de Combustible – Calcular Gastos de Combustible',
      de: 'Kraftstoffkostenrechner – Reisekraftstoffkosten Berechnen',
      zh: '燃油成本计算器 – 计算旅途燃油费用',
      hi: 'ईंधन लागत कैलकुलेटर – यात्रा ईंधन खर्च की गणना करें',
      pt: 'Calculadora de Custo de Combustível – Calcular Despesas de Combustível',
      ru: 'Калькулятор Стоимости Топлива – Рассчитать Расходы на Топливо',
      ja: '燃料費計算機 – 旅行の燃料費を計算',
    },
    metaDescriptions: {
      en: 'Free fuel cost calculator. Calculate how much fuel will cost for your trip based on distance and fuel prices.',
      ar: 'حاسبة تكلفة الوقود المجانية. احسب تكلفة الوقود لرحلتك بناءً على المسافة وأسعار الوقود.',
      fr: 'Calculatrice de coût du carburant gratuite. Calculez le coût du carburant pour votre voyage.',
      es: 'Calculadora de costo de combustible gratuita. Calcula cuánto costará el combustible para tu viaje.',
      de: 'Kostenloser Kraftstoffkostenrechner. Berechnen Sie die Kraftstoffkosten für Ihre Reise.',
      zh: '免费燃油成本计算器。根据距离和燃油价格计算旅途燃油费用。',
      hi: 'मुफ्त ईंधन लागत कैलकुलेटर। दूरी और ईंधन मूल्य के आधार पर यात्रा ईंधन लागत की गणना करें।',
      pt: 'Calculadora de custo de combustível gratuita. Calcule quanto o combustível vai custar para sua viagem.',
      ru: 'Бесплатный калькулятор стоимости топлива. Рассчитайте стоимость топлива для поездки.',
      ja: '無料の燃料費計算機。距離と燃料価格に基づいて旅行の燃料費を計算します。',
    },
    keywords: {
      en: ['fuel cost calculator', 'gas cost calculator', 'trip fuel calculator'],
      ar: ['حاسبة تكلفة وقود', 'تكلفة بنزين رحلة'],
      fr: ['calculatrice carburant', 'coût voyage'],
      es: ['calculadora combustible', 'gasto gasolina'],
      de: ['Kraftstoffkostenrechner', 'Spritkosten Reise'],
      zh: ['燃油成本计算器', '旅途油费'],
      hi: ['ईंधन लागत कैलकुलेटर', 'यात्रा ईंधन लागत'],
      pt: ['calculadora combustível', 'custo viagem'],
      ru: ['калькулятор топлива', 'стоимость бензина поездки'],
      ja: ['燃料費計算機', '旅行の燃料費'],
    },
  },
  // ===== MISC =====
  {
    id: 'password',
    slug: 'password-generator',
    categoryId: 'misc',
    icon: '🔐',
    isNew: true,
    names: {
      en: 'Password Generator',
      ar: 'مولد كلمات المرور',
      fr: 'Générateur de Mot de Passe',
      es: 'Generador de Contraseñas',
      de: 'Passwortgenerator',
      zh: '密码生成器',
      hi: 'पासवर्ड जनरेटर',
      pt: 'Gerador de Senhas',
      ru: 'Генератор Паролей',
      ja: 'パスワードジェネレーター',
    },
    descriptions: {
      en: 'Generate strong, secure, and random passwords with customizable options.',
      ar: 'إنشاء كلمات مرور قوية وآمنة وعشوائية مع خيارات قابلة للتخصيص.',
      fr: 'Générez des mots de passe forts, sécurisés et aléatoires avec des options personnalisables.',
      es: 'Genera contraseñas fuertes, seguras y aleatorias con opciones personalizables.',
      de: 'Generieren Sie starke, sichere und zufällige Passwörter mit anpassbaren Optionen.',
      zh: '使用可自定义选项生成强大、安全和随机的密码。',
      hi: 'अनुकूलन योग्य विकल्पों के साथ मजबूत, सुरक्षित और यादृच्छिक पासवर्ड बनाएं।',
      pt: 'Gere senhas fortes, seguras e aleatórias com opções personalizáveis.',
      ru: 'Генерируйте надёжные, безопасные и случайные пароли с настраиваемыми параметрами.',
      ja: 'カスタマイズ可能なオプションで強力、安全でランダムなパスワードを生成します。',
    },
    metaTitles: {
      en: 'Password Generator – Create Strong Secure Passwords',
      ar: 'مولد كلمات المرور – إنشاء كلمات مرور قوية وآمنة',
      fr: 'Générateur de Mot de Passe – Créer des Mots de Passe Forts',
      es: 'Generador de Contraseñas – Crear Contraseñas Fuertes',
      de: 'Passwortgenerator – Starke Sichere Passwörter Erstellen',
      zh: '密码生成器 – 创建强大安全的密码',
      hi: 'पासवर्ड जनरेटर – मजबूत सुरक्षित पासवर्ड बनाएं',
      pt: 'Gerador de Senhas – Criar Senhas Fortes e Seguras',
      ru: 'Генератор Паролей – Создать Надёжные Безопасные Пароли',
      ja: 'パスワードジェネレーター – 強力で安全なパスワードを作成',
    },
    metaDescriptions: {
      en: 'Free password generator. Create strong, random, and secure passwords with custom length and character options.',
      ar: 'مولد كلمات مرور مجاني. إنشاء كلمات مرور قوية وعشوائية وآمنة مع خيارات مخصصة.',
      fr: 'Générateur de mot de passe gratuit. Créez des mots de passe forts, aléatoires et sécurisés.',
      es: 'Generador de contraseñas gratuito. Crea contraseñas fuertes, aleatorias y seguras.',
      de: 'Kostenloser Passwortgenerator. Erstellen Sie starke, zufällige und sichere Passwörter.',
      zh: '免费密码生成器。使用自定义长度和字符选项创建强大、随机和安全的密码。',
      hi: 'मुफ्त पासवर्ड जनरेटर। कस्टम लंबाई और चरित्र विकल्पों के साथ मजबूत, यादृच्छिक और सुरक्षित पासवर्ड बनाएं।',
      pt: 'Gerador de senhas gratuito. Crie senhas fortes, aleatórias e seguras.',
      ru: 'Бесплатный генератор паролей. Создавайте надёжные, случайные и безопасные пароли.',
      ja: '無料のパスワードジェネレーター。カスタムの長さと文字オプションで強力でランダムな安全なパスワードを作成します。',
    },
    keywords: {
      en: ['password generator', 'secure password', 'random password', 'strong password'],
      ar: ['مولد كلمة مرور', 'كلمة مرور قوية', 'كلمة مرور آمنة'],
      fr: ['générateur mot de passe', 'mot de passe fort'],
      es: ['generador contraseñas', 'contraseña segura'],
      de: ['Passwortgenerator', 'sicheres Passwort'],
      zh: ['密码生成器', '安全密码'],
      hi: ['पासवर्ड जनरेटर', 'सुरक्षित पासवर्ड'],
      pt: ['gerador senhas', 'senha segura'],
      ru: ['генератор паролей', 'безопасный пароль'],
      ja: ['パスワードジェネレーター', '安全なパスワード'],
    },
  },
  {
    id: 'random-number',
    slug: 'random-number-generator',
    categoryId: 'misc',
    icon: '🎲',
    names: {
      en: 'Random Number Generator',
      ar: 'مولد الأرقام العشوائية',
      fr: 'Générateur de Nombres Aléatoires',
      es: 'Generador de Números Aleatorios',
      de: 'Zufallszahlengenerator',
      zh: '随机数生成器',
      hi: 'यादृच्छिक संख्या जनरेटर',
      pt: 'Gerador de Números Aleatórios',
      ru: 'Генератор Случайных Чисел',
      ja: '乱数ジェネレーター',
    },
    descriptions: {
      en: 'Generate random numbers within any range for games, decisions, or research.',
      ar: 'إنشاء أرقام عشوائية ضمن أي نطاق للألعاب أو القرارات أو البحث.',
      fr: 'Générez des nombres aléatoires dans n\'importe quelle plage pour les jeux, les décisions ou la recherche.',
      es: 'Genera números aleatorios dentro de cualquier rango para juegos, decisiones o investigación.',
      de: 'Generieren Sie Zufallszahlen in jedem Bereich für Spiele, Entscheidungen oder Forschung.',
      zh: '为游戏、决策或研究在任意范围内生成随机数。',
      hi: 'खेलों, निर्णयों या शोध के लिए किसी भी श्रेणी में यादृच्छिक संख्याएं बनाएं।',
      pt: 'Gere números aleatórios em qualquer intervalo para jogos, decisões ou pesquisa.',
      ru: 'Генерируйте случайные числа в любом диапазоне для игр, решений или исследований.',
      ja: 'ゲーム、決定、または研究のために任意の範囲で乱数を生成します。',
    },
    metaTitles: {
      en: 'Random Number Generator – Generate Random Numbers Online',
      ar: 'مولد الأرقام العشوائية – إنشاء أرقام عشوائية عبر الإنترنت',
      fr: 'Générateur de Nombres Aléatoires – Générer des Nombres en Ligne',
      es: 'Generador de Números Aleatorios – Generar Números Online',
      de: 'Zufallszahlengenerator – Zufallszahlen Online Generieren',
      zh: '随机数生成器 – 在线生成随机数',
      hi: 'यादृच्छिक संख्या जनरेटर – ऑनलाइन यादृच्छिक संख्याएं बनाएं',
      pt: 'Gerador de Números Aleatórios – Gerar Números Online',
      ru: 'Генератор Случайных Чисел – Сгенерировать Случайные Числа Онлайн',
      ja: '乱数ジェネレーター – オンラインで乱数を生成',
    },
    metaDescriptions: {
      en: 'Free random number generator. Generate single or multiple random numbers within any range instantly.',
      ar: 'مولد أرقام عشوائية مجاني. إنشاء أرقام عشوائية مفردة أو متعددة ضمن أي نطاق فورًا.',
      fr: 'Générateur de nombres aléatoires gratuit. Générez des nombres aléatoires dans n\'importe quelle plage.',
      es: 'Generador de números aleatorios gratuito. Genera números aleatorios en cualquier rango.',
      de: 'Kostenloser Zufallszahlengenerator. Generieren Sie Zufallszahlen in jedem Bereich.',
      zh: '免费随机数生成器。即时在任意范围内生成单个或多个随机数。',
      hi: 'मुफ्त यादृच्छिक संख्या जनरेटर। किसी भी श्रेणी में तुरंत एकल या एकाधिक यादृच्छिक संख्याएं बनाएं।',
      pt: 'Gerador de números aleatórios gratuito. Gere números aleatórios em qualquer intervalo.',
      ru: 'Бесплатный генератор случайных чисел. Мгновенно генерируйте случайные числа в любом диапазоне.',
      ja: '無料の乱数ジェネレーター。任意の範囲でランダムな数字を即座に生成します。',
    },
    keywords: {
      en: ['random number generator', 'random number', 'number generator'],
      ar: ['مولد أرقام عشوائية', 'رقم عشوائي'],
      fr: ['générateur nombres aléatoires', 'nombre aléatoire'],
      es: ['generador números aleatorios', 'número aleatorio'],
      de: ['Zufallszahlengenerator', 'Zufallszahl'],
      zh: ['随机数生成器', '随机数'],
      hi: ['यादृच्छिक संख्या जनरेटर', 'यादृच्छिक संख्या'],
      pt: ['gerador números aleatórios', 'número aleatório'],
      ru: ['генератор случайных чисел', 'случайное число'],
      ja: ['乱数ジェネレーター', '乱数'],
    },
  },
  {
    id: 'mortgage',
    slug: 'mortgage-calculator',
    categoryId: 'finance',
    icon: '🏠',
    isPopular: true,
    names: {
      en: 'Mortgage Calculator',
      ar: 'حاسبة الرهن العقاري',
      fr: 'Calculatrice Hypothécaire',
      es: 'Calculadora de Hipoteca',
      de: 'Hypothekenrechner',
      zh: '房贷计算器',
      hi: 'होम लोन कैलकुलेटर',
      pt: 'Calculadora de Hipoteca',
      ru: 'Ипотечный Калькулятор',
      ja: '住宅ローン計算機',
    },
    descriptions: {
      en: 'Calculate your monthly mortgage payment, total interest, and full repayment schedule.',
      ar: 'احسب الدفعة الشهرية للرهن العقاري وإجمالي الفائدة وجدول السداد الكامل.',
      fr: 'Calculez votre mensualité hypothécaire, l\'intérêt total et le calendrier de remboursement complet.',
      es: 'Calcula tu cuota hipotecaria mensual, interés total y calendario de amortización completo.',
      de: 'Berechnen Sie Ihre monatliche Hypothekenzahlung, Gesamtzinsen und den vollständigen Rückzahlungsplan.',
      zh: '计算每月房贷还款额、总利息和完整的还款计划。',
      hi: 'अपनी मासिक होम लोन किस्त, कुल ब्याज और पूर्ण पुनर्भुगतान अनुसूची की गणना करें।',
      pt: 'Calcule sua prestação hipotecária mensal, juros totais e cronograma completo de amortização.',
      ru: 'Вычислите ежемесячный ипотечный платёж, общую сумму процентов и полный график погашения.',
      ja: '月々の住宅ローン返済額、総利息、完全な返済スケジュールを計算します。',
    },
    metaTitles: {
      en: 'Mortgage Calculator – Monthly Payment & Amortization',
      ar: 'حاسبة الرهن العقاري – الدفعة الشهرية وجدول الاستهلاك',
      fr: 'Calculatrice Hypothécaire – Mensualité et Amortissement',
      es: 'Calculadora de Hipoteca – Cuota Mensual y Amortización',
      de: 'Hypothekenrechner – Monatliche Rate und Tilgungsplan',
      zh: '房贷计算器 – 月还款额和摊销计划',
      hi: 'होम लोन कैलकुलेटर – मासिक किस्त और परिशोधन',
      pt: 'Calculadora de Hipoteca – Prestação Mensal e Amortização',
      ru: 'Ипотечный Калькулятор – Ежемесячный Платёж и Амортизация',
      ja: '住宅ローン計算機 – 月々の返済額と償却',
    },
    metaDescriptions: {
      en: 'Free mortgage calculator. Calculate monthly payments, total interest, and full amortization for home loans.',
      ar: 'حاسبة الرهن العقاري المجانية. احسب الدفعات الشهرية وإجمالي الفائدة لقروض المنازل.',
      fr: 'Calculatrice hypothécaire gratuite. Calculez les mensualités, l\'intérêt total pour les prêts immobiliers.',
      es: 'Calculadora de hipoteca gratuita. Calcula cuotas mensuales e interés total para préstamos hipotecarios.',
      de: 'Kostenloser Hypothekenrechner. Berechnen Sie monatliche Raten und Gesamtzinsen für Wohnungsbaudarlehen.',
      zh: '免费房贷计算器。计算住房贷款的月还款额、总利息。',
      hi: 'मुफ्त होम लोन कैलकुलेटर। होम लोन के लिए मासिक भुगतान, कुल ब्याज की गणना करें।',
      pt: 'Calculadora de hipoteca gratuita. Calcule prestações mensais e juros totais para empréstimos imobiliários.',
      ru: 'Бесплатный ипотечный калькулятор. Рассчитайте ежемесячные платежи и общую сумму процентов по ипотеке.',
      ja: '無料の住宅ローン計算機。住宅ローンの月々の返済額と総利息を計算します。',
    },
    keywords: {
      en: ['mortgage calculator', 'home loan calculator', 'monthly payment', 'amortization'],
      ar: ['حاسبة رهن عقاري', 'حاسبة قرض منزل', 'دفعة شهرية'],
      fr: ['calculatrice hypothèque', 'mensualité crédit immobilier'],
      es: ['calculadora hipoteca', 'cuota mensual hipoteca'],
      de: ['Hypothekenrechner', 'Wohnungsbaudarlehen'],
      zh: ['房贷计算器', '月还款额'],
      hi: ['होम लोन कैलकुलेटर', 'मासिक किस्त'],
      pt: ['calculadora hipoteca', 'prestação mensal'],
      ru: ['ипотечный калькулятор', 'ежемесячный платёж'],
      ja: ['住宅ローン計算機', '月々の返済額'],
    },
  },
];

export function getToolsByCategory(categoryId: string): Tool[] {
  return tools.filter((t) => t.categoryId === categoryId);
}

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((t) => t.slug === slug);
}

export function getPopularTools(): Tool[] {
  return tools.filter((t) => t.isPopular);
}

export function getNewTools(): Tool[] {
  return tools.filter((t) => t.isNew);
}

export function searchTools(query: string, lang: Language): Tool[] {
  const q = query.toLowerCase();
  return tools.filter((t) => {
    const name = t.names[lang]?.toLowerCase() ?? '';
    const desc = t.descriptions[lang]?.toLowerCase() ?? '';
    const keywords = t.keywords[lang]?.join(' ')?.toLowerCase() ?? '';
    return name.includes(q) || desc.includes(q) || keywords.includes(q);
  });
}
